apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/mlflow
  - pg-cluster.yaml

namespace: prod  

patches:
  - path: release.yaml
  - path: httproute.yaml
  - path: pg-cluster-backup.yaml
