apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimaldo-frontend-ingress
spec:
  rules:
  - host: minimaldo.nishantlabs.cloud
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: minimaldo-backend-svc
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minimaldo-frontend-svc
            port:
              number: 80
