apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/minimaldo
  - pg-cluster.yaml
namespace: prod
patches:
  - path: httproute.yaml
  - path: frontend.yaml
  - path: backend.yaml
  - path: pg-cluster-backup.yaml
