apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-nishantlabs-cloud
#  namespace: traefik
  namespace: istio-system
spec:
  secretName: local-nishantlabs-cloud-tls
  dnsNames:
    - 'local.nishantlabs.cloud'
    - '*.local.nishantlabs.cloud'
  issuerRef:
    name: cloudflare-clusterissue
    kind: ClusterIssuer
