apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn
  - ./metallb
  - ./cert-manager
#  - ./monitoring
  - ./cloudnativepg
  - ./istio
#  - ./external-dns

#  - ./actions-runner-controller
#  - ./pihole
