apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn
  - ./metallb
  - ./cert-manager
  - ./pihole
  - ./monitoring

  - ./actions-runner-controller
  - ./cloudnativepg
