apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:wWUGEPC56/ozoMJVdV4=,iv:loYX4istvOnjFp/sGHoBJv9wBJW37JUdQY6RtAG0RcU=,tag:MhU48FTr5oZf556okKQ6DQ==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTnNRaXB4bDNrd2RCRXFU
            aG4rSERSalhPc0hRY1lTQ2RVVFJmQXhaMWpBCk9wQzUvRFlHbWRCRmhjditnOG9x
            VWR6RVpNTFpsZm1odGd5Qk5OVzZ2L2sKLS0tIHViOXlpT0IvZEFNcEpEUXNZRURV
            bk1KdmJsdi8rekFON2RlbzhJN1M3MTQK9IHZxF4qzloJ9c64mhcIRr27voerNaJO
            o1yMw8EyxdDkuu0jmTyChULmGv6E8o0lBJmKju03Myl2TcKwPsN0jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:56:52Z"
    mac: ENC[AES256_GCM,data:718mA3UGrE5DmV+hmAjqOGK6rRUDTlGy2XCz6SWxVqcp0rH94t+e7yE9wiL7FEAeQVbDCqFwweR2o10Qg7TdfmYkyZU/y53Z8IfHYc0l6jDOO12xeYxfCdFhM1JFIhh+jFfxFu8St/kiQsKpqUsFAyOujkAcI3jX5/5gJW9mRFE=,iv:2A7IoHhjYaym369iRJPKpcqQcwApnVUhOT7X/qf/cjM=,tag:u8p5bY3dEGw8SOGWoK8ErQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
