apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:2qiCGFFXxKf552nqNXZl1LKnGEPCx1PkUah/oFWXSUSsY0FqmdsYQg==,iv:RkaC5v4vfR+lKaLATp6sDJEIJjP/u4cY1BqBvtDnWFA=,tag:2fX1DPYKBUeW901aLP7j8w==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cXlRN1QwVC9DYUtIT1Bi
            UEswMVBsS05BcmhsWkJaZzU4Mm9PaDdUemxVCjZwK3JoTFBWQ25qUWZKUnBnQ210
            VjgzZU1NOEpyZHVmR2ZFT0RUYmU1M1EKLS0tIGtlUkdKZ0xhc20xZ2pmek45ZFlx
            L2tPOVlmM1pkeThyN0pJN1dmai9GYVEKbu1xQJQ6+IYLK+bzkRikaSSaIwey9g67
            GoeWnVag2SLyRwXwT8oOORPYgz/AE1agshxSn+dzuHVIG21nHB3zOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:51:31Z"
    mac: ENC[AES256_GCM,data:rrSl22MgWbhBlY3pEvO7NTzpQ+5RcB1kHlyq4D8alCXgiDbhxdaU3uprPxUM8B5WkMbWOL7POQLITJtW2V3Ub03YpiFfNtTvnTfCWQctQyYvHdo4MIea4xmeLMGiF4YJdumgU47KlH79E4+/fdkDJWjzB706x36c6TiunxWj2DA=,iv:X6K1+r7ol0SkAa+SxyVGzhkxXVtCAlVssOZrXfRzIRw=,tag:fAGkfuM9JKurTP3wo3jbbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
