apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:1OpHJNbN8CuxufthEgJMR0P60GHHMFvwndfhsOK21NSRuGcY6Lzt2A==,iv:Gay9Ic5XMRLRd0lE2vEnWrBZF1hUG2BLq7kU+ssygSg=,tag:5OjFOqqn7LI5qHuPl51x6w==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneFpLTlRhVERDQWFOcWZw
            RWErdlZ2UkJlelNBTEl1dXBJRnBYNllQZWlZCnJKSDV4MHlwc3dKQ1FRR2tXdUp1
            UnYvclNCSTVSY2dkbWtzcGNJTk44V0EKLS0tIE1Jbk1oR2NMK0VsUVpmK0h1NlVW
            UjdPZzV3dzlDZXgrc2NMalJNQ3hhSkEKAFAP9WrmZw6pzmyUHGdieOsbZy0LzrG4
            8an+IwBLTuL/zjoE8kr6u3Hbsr6aHVNhf4Ai/5VQvP81WYsTiPvRWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T09:08:21Z"
    mac: ENC[AES256_GCM,data:ahf9cef2qYZL955totCeMHrzDxPNEoDgCNfSDvxSpEFDnJDM96MIDcm+9qOuYeDziF3sUkjsIvBs243P/ZzQJ4AoJawvu+sQCTIyAuDspHIQF7UQD682bHh5b33E6SR9WfL+2KyaEFmzxzasTP9JGew2Dxg5Fjo8VV581mBi+LA=,iv:AAGfltDHdOlcqQC4nCmvu6GEaoepqjhzvqPjFRL4LjE=,tag:wTFRsWYm+AHl3cWpElnjvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
