apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:c+3r2I8qGHpchwUGqt/dTdUq15T3yp+cxM89V7SGo1+XkKL4LoqCLg==,iv:RDsWkd18fnFfMhjWD6kSXeNCMJnvttM5vjW7KlQYOl8=,tag:eJhU7EQ7NRqAzK734vimgQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRHc5dDI0dnB0VWEzT2VU
            UTRPQXVOMHlZMHhTOExmcytUdGN1OEplMWh3CnJaV1FRcnJhM2RiOVppejZLWnBD
            T2oveEdYZkJ2dVgxV3JCZXpHVFhHNDQKLS0tIC9IQUp1S2xRSXRyVHpLUUpuK2to
            RWcrc2k2ZDM3TWJtdVBMcVdLSHROQzQKXyiQF5LEjbACpwstDlE1OIM9Ae93ooyS
            mNJsZD/tR4+xk5dhzH39XijX7OVvSBtgwDXHk+RLYYJp7gWe1dyKeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:10:32Z"
    mac: ENC[AES256_GCM,data:OoXQ6FUGWhRrrOmxbgXqAcB8z1VckC2uAcHdBhdX2Av5nvpmk5MMmwZVu5VWY/d6FltksUGggVenpDe2me3YjhLfqVNz6Ud20wBeWGEVlsjf27C5wIpvNXx4poZjdY8LcJvFG8SimJLxZZMfYrXkvZHthlN5fdjnl5ADg3S6e4I=,iv:pV9ub1oyCa1mmeHxH/0PlL8Rohw46mOh6EjKliJ6Vtg=,tag:mvebxGxDkTnZ67tX+C9a4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
