apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:7Ngh+eDT4PRE+YwvPHZghS3hGKzpHqnLnTmCviurjQ/npnaDULZfFg==,iv:03hUdgqASxNW5uX/v7pKFw67g0oRPhAOGkcd+sfLjS8=,tag:MtsWHb0SD4tSaNJpcRbz7g==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeXpyTEtWekJBeER3QzBL
            MHdoSEUxODl6MnYyZUtRSlJxUE94TlNNbHlRCnJhUkhjeWdJNlJhMzl6U2lhSUZL
            NlkzN2FqV04yREUvTGJJTUIyTjJUOE0KLS0tIHNacU9GNDBjaXJZMzhKL3Iyb2Ny
            OU5YdzZiWkI1TzQxY1JLV1lGMDJvNTgKHAq+1nmNoeU+RSoBEZD7grckTqY9wB/n
            vbCiKSxhnV4/rARjFMUj662A7hl6+Ng5H+QMYpevUPgvhZuPrdr4xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:53:04Z"
    mac: ENC[AES256_GCM,data:89vIONKN7yCT7b2/EIAiIY0OmH4PwP/SEyoq2liijJbEHh1bt66QB9uSsR6FYQeUgb7VLaoZDKNRgrb+Oml37PRX/7ta7GDQMruQzWFGfXZXo0kZYDjpkXRBdQqL0+HRkp1/xWmHuJJc2zLRSJPjL/w6gWySKVSqb2J+Kqyc29Q=,iv:Y20qDJHCTHj5Adj2jYiyI+2KBjZ0iI6iOobfDV5zrow=,tag:8RIjYah52UwrMbM2Hq5ryA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
