apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ThSKgyE3hn7d+p+we1Ayz/egS+PIIiX9JYwSq23uW3THz2zg6qneTQ==,iv:PRRHiQNMoC1jnvsIn/EDGa+aLCU2A5Yt4arSZRegjSE=,tag:3rruJZ/pnL9HGy7Yx0ikrQ==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSFBGb2hadzNUZWhEQlpm
            Nmg0U3V6V3hncU4zeEN5Rk93SUtXK21rK0U4CjNadlNYQzZKZk0rKzNMQnh1SXRn
            MG5EREJNdlhELzM1VERLTFBxSVM5RDQKLS0tIFVEZFpTZWJaVWlBaCtCc2x1S0d3
            VjVZT2RFNTBXSGRueTNwNUhtaWlhdW8Kz32C2AGNLHHWuW9EE7sZ7XiPJc/lgr2e
            HRc1ZBjqkx7inLPu1RQbZ3t3dknbYVOGw2j78kFhtvWZiZnpGkwqYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T07:47:02Z"
    mac: ENC[AES256_GCM,data:GDfSTCbVwhDUOfQ28D4mh9uwc1tlLk/yfIuKlN5fTOzWbEaa9El0PSssoLoVY1eZVU/IuYrJ0bgwnSi6bHvOZPq96wvrCGnCTyX9GMGKvrFDIkq9WuWcrAG4r78MmHMUKGsk9rCLoyEclaflNodGiUckc2OWHyugKNyqPkZTTKY=,iv:j4QVu1Drkx1+jMNEGc4W2iLY7rDDJHn6oNDCgVWx9jk=,tag:2cPe0wM0u5Qs3opZ8S+WpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
