apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:2TwXSGsa95QyTeQIyBpouDFfvls7T9Fhi+BG7HS0kxIs/ri9lF8L9g==,iv:cTUGi55CD5d7g1ytQTqDuTvODCgbaB7hmzidu0PNalw=,tag:61eWFwLKsiRQZwEK/m3kVQ==,type:str]
sops:
    age:
        - recipient: age1khzu05szp0um38uvn50knwv8w2puy64a9f6f3f0mjtc2lzpmzgqs7m23pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOExCcWtYRCtPVVUzb2RT
            cklaT1hLYzdMTnVqSm9KeFJtL0MwMGpuWG5rCjBXdFIwbXVJWWE1Y2lURlhiZ1o4
            UnlnNmNsQjluU3pybFdRLzdmU3lMa0UKLS0tIGQwckNxc1MvL3VwZmpaODhnc0h1
            Y3RrelMrdXozcXUzTkF0aFJTekFzT00K/AA39xuyEaGS5q/hOp34GN2k7xAP9dF5
            Mmdr6bAiCWg9anSmoXVE/F6Rdshkrfvz7DQ9LVjxTe1w6XhhbOWVlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T09:25:01Z"
    mac: ENC[AES256_GCM,data:3PXBKczsGuZcveUsS+5uwV82LeKDpOSiTXqyItFJ+1Z50vNwqVQYBbPbNL1OOu32Vg0Jp79LB8dSwkfHtAjSPrAx0txr98rndN0OtbSRslVUyoFj84uXVQ8Q88d7kEj5PYUIwjpQb709EVwiyPKrAxccVGs9Bu0HOoISAO0svDM=,iv:Gam39dgFChnsOqqIsF6nOGMEONCgqadJjOch+ylA1xU=,tag:19i3yre3E7+pWXztEN1kCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
