apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:XQZilgRYGPMGnLgObSdiRfH4rsx0/9zPXl+kMXSwjgGkey+adbsUgw==,iv:fYphZ91VFlq4e/5wk9YEIce5bsMJmBHCYXHVxEmYxfA=,tag:WWUK1hAMU4qrdr7qVfgxPw==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeWMzM0xxamZBT29tbC9D
            ZWZRQTlJeXRJdnNyb2FrUS8renZMSXhucTJ3CkF3WTQvQnJxQ0hjVmE4dy9SSUhw
            Nm5IQlNjWGVlUERSMzZQekJ0QVMvdm8KLS0tIHBhZnJnSk10aTJQV011Y1lNQVJn
            ZHF4WThFUmczWnVGTlkzbDJvUC9ybTQKqJ+UFA2OGZQRYV9HTTu1oxIDGaAxYwgv
            iCkgqHoCkIws2r9oQ1wUw1QjwblmGLqhOaRJ6PmJGiqt7z6M8usx+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T20:07:23Z"
    mac: ENC[AES256_GCM,data:RAD8xm+Xpem7HWJmVqZ4wjtNKhObts2uimpcCvfP2+a2NGDaUA/fVANzB2yag/dNVilb8O7ksAxrVGlJM5gRpED+kh6iEmJG4pN01JdsRw/g/Fw02dbQRtmK2tigynwEXhVw3UJh4vaziHLQ0RZN9dNd5ixuM2CGofcXOxhNwxM=,iv:i8WEn1hI60HO/RxuPCmAd8nsfuxzf6CihxxTsafZA1Q=,tag:/k4N1mA4lr30rmogh+TbFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
