apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:K89eoHiQjtT61GPQg7I9oASqGTRq1HF6oqLr/6d8eyNW6kuNwRONcg==,iv:u+akyIKelWnfGI+4YCVpz3xROVNfmyf+wNBx0NgHueA=,tag:bt359Eut+1FID9YIfkn9NA==,type:str]
sops:
    age:
        - recipient: age184uxhteulqapkl0ue4lpyyn5pxlpwteynxp2367vykclxxzvxyfs6a66ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMzc4cG1rYVd2QW9tRU53
            eW5uZWxFc015U3NiSTI0Y0FmczdFT09LZjN3ClpkTm92ZVg0OUdVQnl6L2NSZVda
            SWRIOHdEZHAxelpMTkZ3VU9IYUI1S0EKLS0tIGllMzdjRndXVC9sVk8yOXdIczQ5
            djJIVStRamY0cGlmUXpzUlMvZUdURmcKhWlfhLcoZhNrgT3u6BqtHE3NgQdBB2KK
            0tzEl1Zegyhlt5tpzG3qOTCgpmqh97oK4XMlq/eD4PNpisYMKf00lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T13:17:47Z"
    mac: ENC[AES256_GCM,data:JrkKgp2fZ1B8sf6o289uxKbM25VzNQRsL3cWDoqXeV6QLQ5ueJZNBXPNJ18s/y/cbhj/ylUc47GfJq1BsROo8CDIEaKANpIle/P4TqKuh0gfQuxwWpQhj2rTMgVAcM9T9A0OA6B2iJo7rhTE5Zvw31GTa2iDc0C0CB0YsprrndM=,iv:ZfG+cFzQW4QCJ1xxSZNKUg7TpxsB7YfFucGQhJ/Kk50=,tag:cKyv6AjWLFA6S6prUSSMsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
