apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:G9SqgQD5naIwnNKGoIrSzwsLJL1em/5F2obvLuth0vVYaW7W5/oYKQ==,iv:nVi56OkIA0BY38XmbGGI00rg42PP3/RrYH5FIhCPYN4=,tag:ddTXLStN8LuNkjCv7PouUQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVWFDQmdzK0t5SDI3elNw
            TUI1SXJqWEdjZGpoQ0lhUGZxMW1YK0pqbmhBCndZV1piQXZUeFFHVGNYTmxaRmdT
            dFBUUk90TU1RcHNvN2hieEI1eU5hcVUKLS0tIGxoblVHUXNSTitYTXB3Nm9HMDlr
            VE1Ra1RhTlgrZ3l6SEI0Um03d1pQSkkKbdD457nptuXEkX/Kt7+FB8XU6EnTOf4b
            QJvqxLJ83Gos7YXE0Tucss2GJodWuWzn0Q98AQZZyl6OEFYJfp039w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T10:21:52Z"
    mac: ENC[AES256_GCM,data:jyplXMRp6KrYtMAtPyt0E5w+FCJ5iAsBIYNGtYjAIjJiQzS6WG4+1YHX0lTN/OeqQn3U71TSW9Ll1A1TQZeZewHCWb8L0jJFCiKouMKJiwCCXYWx3lVBHyvwDgi/xQFKVCKRIeuJq1dZFeSu1j1hkrJtl/5AfpDw6acxkLUnFw0=,iv:ZEOY8AIKiB907VyA1baE7244NKKo4ZoAjJ4xXwXKhEU=,tag:61xbt+HYVcGxc+XabtxNZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
