apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:zpcUoGfN3J3Jg8HhXBwRCHo5sRX+yoc3/PsQQbGKZT/XZIYQoHphwQ==,iv:58TYNawT2O+eG8WiEZZ/JJ30BgjaO47bc+s4NcvE4Qg=,tag:nqLDcUneasuGdmMQrita6g==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNEJjUkg2WUxkL3Z3Z1Vj
            Mk9XMktETjJ2azVLNTJMQUlpMXVEeDZIZ3pzCm1GYjBIWWJHaGo5U3ZpSE84UFpn
            UGlackE2TCs2WE9Uc1JLWmxTZzhHZmcKLS0tIDQxVmd5OVpPRUFPdHB6eEN2OG52
            ck1uZm0xTkZ3RXl2N0NvYUwzaGxOaVkKgkNhma2UoU5x0CR7RO1Qi2NgSbl6b5l9
            DgeS4lssFyTucG0msHui/hYDbKqAAQ5ztxoWliV9Ey/tXe8Pa4Crow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T12:42:02Z"
    mac: ENC[AES256_GCM,data:PR7arDP1fO/lX7dKrKc8tn3x/HK83Y0rOeDK7uCyKFY/yEh0mklc/gmjAG+qNTJD/p4++sNEtvBW1u7tOX4aW7f9YZmnFeleXmsRDYPfgxn8CnDSSdukeqtzQZaYEdFgHmQ4ZL9DDSede04uLN62yWNb1TLknldMKWZ915OEXqQ=,iv:ILdLt730XykPeQ+Epl0CMI+S1WO9v7stR3u+x0b+UXk=,tag:h4uNPeLsY+bdkV48rb7yuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
