apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:w+wtFWLGFZ6Nj7CvqJv0WLnurGi/S1OfOZsNiOymGFa8FWwBQdLTjg==,iv:Mfjnywxb793ZZBoRCpRL7tr26V7YSzMA5fFT/T7TokE=,tag:rKGZsIfDa+TgGfKAtEm73Q==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNDFqTWgvMHRwaTdnU3Z0
            L2NTclgvTnA3Mzg1cDBlM0k1NlNYekdUdHlNCmRCQ1EwcmQ5UVBNbml3aHpuYkpt
            RDE2N1MvYXo5Nys3ZTQzK0hVSnBFNlkKLS0tIEZqYjcvK0YvZ2ZxMlhvT0VPZWd0
            dEVDQjZ4SnJFUDN2SWk2Zm94dVpsVjQK+wlY/p+HJepKqXVHMYkJ5s/tV7mjgfQJ
            5El2tEtqNEeeZ8cuk9sWQ2J4W/NK7DqSSuJEc50mqBkn0Wb+IXxCPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T14:43:30Z"
    mac: ENC[AES256_GCM,data:WI8Ljc71yhGe/VuTtM+SIbFjbFSSqCAmIdR95494X6S9z09hmIeCYlvQrlZ7Fsq8wWohkPDHYAefFO5AXdTUDDkKIOPcWFuNI69P6J6fqgOkEcL9hl9r6c/T2CRkyKHa45yRgXlhp+nM8WdH+8wq59GzQyV8jLC6/amrttGKxyc=,iv:TC01j/ojWSnbhWyJ3hYA2Z0d5N5vIYB3iNFOmIYCu+U=,tag:rYrpNkOimUTlT8VKcei+aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
