apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:4O6OsrhCHrzMaDC/u/2LEN+ns9r7iaiQPZCH+p9/2c1C0iKlOlLhMA==,iv:kzM6ze964v79dt6qagCDZS09GOxNbsaZt+J/ikLZCcE=,tag:AHJ9Cpw6c+1jEnmcdlcfjw==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UWExNDdPRlVxL0hwRjIv
            RVZUaGdic3U1TUVKWXpuSzRpRzFqUm5CbVNVCklkWGRQeEtUQkhmcVE5YnhuR3FV
            aDFFQnFoNXBMSEtiRk9xcU5QYXlsdDgKLS0tIHhWc2QzYm1Tbmt0SmV4UTdEbDdy
            TUFPeWNsZmU4WkNlRFN1Q0xhQW5NMDAKEdjkAs76WN/sqY5xUdx/CQIIXssq64Jf
            8eMruaqi+V9Fx2s72L15/UeoD+xrCwr/tR1CI0gER7Uj6KYInD9R4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T15:09:28Z"
    mac: ENC[AES256_GCM,data:/ky77P8KUbpPvi1888+wnHMD36IZo7HXJbfDJ8iqcil0LZIY5JQIcqN3AlffTpgFKTs2R/2huvK9qIYVqcpqlGOUNh0+0sD8MXsmNYZCf4SOUFNdNV7RaBUg9aRBRzBMPfcMUWqpmfH5UvrJXfI/jtxuvWndNqxJ9eBThzsNmro=,iv:JrMxLm2xXfDKxLbt43HSzQ4ve76rX/AZu9dCt7B6jtM=,tag:U7yV4E1y4c3pelfGp1olXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
