apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:kEYNGo5yo/QVo71Snbb1jMi6A/1mNWghqtFN1NDGTN6Io/J+tbjdBQ==,iv:W6HRYMWcFNqXwl6psLUQoFgVlw0e4K/zaNtMbOOD3Oc=,tag:DV0qZv9Lc4ZHf3udYz9WPw==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U0ZnV1JZV2hnd2FNUFVz
            S1ZFZUdZbS9KMytwaUNDbk95YzkwRkxJazFvCjhqbzNGUGZzNWRPZ0VRRms3L3VF
            T0hKSHFQWEkxQ2dSWUxPZE9yUnBLMk0KLS0tIGdXeFpHWWVRVUVPWjlLeGx6YUoz
            OVpTUmxYYkJVelFnWVVPUTcra2cyN2cK36+/S+JVjLBZdqAEQ3heA2ON/uvZriBH
            IWpOlOmLX4TlpC4cCbCA9bOZS30egJKxb7sJWBY+/mJzQG5WlkMevw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T17:32:11Z"
    mac: ENC[AES256_GCM,data:XGP679+Dkxe+yHUHSqxoO2xLkcRXzd2efDTIZpbggaZT/eU/++UlrpONq2E5mqwDneemvQ2vg7d62dOWrauMxrzNEHbcZ3iXFtDJeNmJUD/Kk94r7wlfspO8a7foxg0KoeOoe71rHLkevek3HYwtG9rH5XTeFt3LsyyX7Pi9sw0=,iv:v5ikHRoSmbVNHNcKz025USsxWudNcuhlsLeq3j7Z9qI=,tag:EwYgfgmneN8Ye5kTe5kBRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
