apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:cO6qYdTykDRjd/KkXLT8FAu+Y9ckpOUXhePOR7MkyOFHlYNyMjUBcQ==,iv:UpKBgCksYW/NVCv1hBnJrkRhtUnRRGWEN1Xm5xdHhys=,tag:QRYPJgLH9aGnWEapzfyVfw==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NnJQUys2a1BIb1RvNGlX
            SVpoc0l4Und1bXNtUmVKWDZ1UzRpT0JhcGc0CkI4Q05kcW5kbWhPU1d1VkFJWUZL
            N2o5Z0hERStsYi9vS1VxemVveFJJZ2MKLS0tIHl1OVVCQk83MWhaUE82RXB4Vi9l
            MTIzV05zdXluVmRnU0ZGWmFNN1FVc2cK+Mlf5TILGrxDOHQhJW782TZhieEj3gYk
            Yb9vQyempzcM7xXxW6jP5r9Vm2ec+2JlS5/ME2tkYHl7DLOqcSeI1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:06:25Z"
    mac: ENC[AES256_GCM,data:exhFmj270NJBxJvP7Jyfq0GnDPF3K3pxfbWdEWuCj6VNQaJMATXl8ciJgTpHuLvSSdn11fFi2OSqY3XCpcD9aVxXp8o+PI6N8q4xbg8+5veBbe87v8GTGLBLOvY5UqAARa+D3l2pzfRFtqckSg7KkblhNriu+ZS2y/M4J0dMXCg=,iv:ewGOMj4+zQnGW+0N3cBhEguI6kRfwdvVTjPinALCVUc=,tag:3zJqRafuzqvBTmoIkcoxUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
