apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:MnEYzP/NkawwNQ4zL1i2uZCwk4agMuD2Wh60f/cmoLGHWf73k6HXOg==,iv:AFIk07n4V5kvLBC0t0A8J0q1Uunuvd7U+QITZZzQVTI=,tag:nyoJ9k+HekEyCVaGKA12Kw==,type:str]
sops:
    age:
        - recipient: age17suyynszxtwggy77kaky3rqtpc4nn3kz9xgstlrd8rwz6zqckasqzmpe7e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVnJSb3NtcVZwS0FOY0Zm
            aEVHNG5HdGhDNEhBT29FMlgyU3VSSnZUSGpVCk55ZFlsWGp1UlhJdWZrZGZ4K3pD
            N0tWN0UwSnB2SGpPRkdIRDIvOHZ1cFUKLS0tIGVacTdBUVBZZ3VUTWhqcTY1Sm5I
            S1FLZGs3b25wZ3ZuUWVWNXEzUFJJdWcKrPmDSHdkyEvHBmhuhii3fsKC3ox2SWmQ
            UE1V7NtUYJf8qP4aZOipzyYIO3CsUwFqMWagk67ViD4om8axWYOxPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T11:58:25Z"
    mac: ENC[AES256_GCM,data:4KZKiWCJX6lBNypwPTNBE6kxJGEOeS+kEXwnTWwD397JbMQisES/8wM+BzJnQYuxjNUw0IMln/h7jGx0b4Eqcjl2Wu5d+dtjxoiv+0h0+KonHlIvG9hxuR35sB/Lu9rAffQm9iQH6uqtZZAD5dU3uQkm7/+2GgDaAggr91RVCLM=,iv:qLUonjn/NhhzWLOMHlmGNCejpdvN0262xlJBbfY28Fk=,tag:PMTd56CeUz/T2CBMowndeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
