apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:QlCONqyLfhzWPz8vvY9hkZZo5/x2KvjxyCgdzTTt3lg2MC9ulJWTzg==,iv:Tb0H384YP3R7hwcjenLYrqGuO4T2OafvVQwxz/H/+eY=,tag:lEllgptMkvUUJoiJaIcoMg==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NkgwUFd2NkdJaHJ6c2N6
            V3FxUHk5cVNqZEpzWXBNVlNrRzdXK1hJMlhVCktzcGl6RlMwVDF3UkY2d0dnb3M5
            YW0wTlJtSlpkbzJObCtzRzRFcTN5S2cKLS0tIHJjRGR0TjZ1RmI4RmlVajNieWFI
            NkNkbm1TcjNHVW82VGN2aVBJUy95TkEK5NGFzRZuWYRp+SS7tEeGy9fNEgTBd7xw
            cBSjq08/TgD4YFjAbkvkp5OzSN2ihVvgWJ9KV/WcnOoNkU4sSCv8uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T14:48:58Z"
    mac: ENC[AES256_GCM,data:2J0sj5esLVlQfr84vPpFU8j6GP9rg+rSf8iOj5al04zVuL8UU51aeVuKJ+o4RYFg9PMkzjAGds2GE99NX+fZwE5uWj9QX0b2Oo7eNAgc5WM0ggavjLRH+Ua3DrkloIRXU+1fjf5C93TOCcj7xEYaKGuAd/zsh2ARPuwW7nvrBgI=,iv:3QmQceHnoZr/vKTMjFmBL2vBqblRUPMQVT/XA8fC6eQ=,tag:unKdGT/J9rpkL8Zlo+PQVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
