apiVersion: v1
kind: Secret
metadata:
    name: pihole-info
type: Opaque
stringData:
    pihole-password: ENC[AES256_GCM,data:q4tWEp2DUSKMlKcpilA=,iv:H7xxBwFo3A0qAIDAWfHRfuYYSYz1BH3OfRf8znAKbNM=,tag:RGcaP6cQhqTlcHqy2orLCg==,type:str]
    pihole-server: ENC[AES256_GCM,data:m078f/wkMdyM2LpKcFp3J3vTRnw=,iv:yY88BNXuKlCMlILy99EB/TfCQayZvbdffAc3atGWqCE=,tag:dJvj12GYMxCzHrjc1gO08Q==,type:str]
    pihole-api-version: ENC[AES256_GCM,data:+Q==,iv:Ti0oMu4I3/8ga/9i1ybcNPaHe874l8fmAC45yP3iiDI=,tag:pnmGEfH2xcqlZdz41ORW/g==,type:str]
    skip-tls: ENC[AES256_GCM,data:xM57hA==,iv:5Qyr8HRY4qbphNbB7HicedbBpGt5tqP2UJwcYaNjqoA=,tag:NYKdvCiR9JVW9uM1lLUoQQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWm1xR0t5UDhGMm5Yd2pw
            dSt5cW10aWhVZUY2QVRyVFlSYW43VUpwOWs0CnRTWXAxbFZxV0JoVXUvZkU3ZHlV
            K1hqWnEwTWZPOEUzbEYxYUQxcDlXZXMKLS0tIEN2L1k3eDVId0lRNS9tVlh4cHhj
            ajN2bUFSN3A5WGNLOFhsSkN4NmFYU0EKeKX6nlIYE8bbF6V8pRwc8nBkR11/FrI0
            7IsPqQnqTQw72plWsDlz4vll11VOc9WcvEryX+SRs3vOmfSU2R66qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:06:25Z"
    mac: ENC[AES256_GCM,data:BSmN70M/eOUMcjkMyBtH9SOmp0UwRhxltUIRNZXn449S81/BrbcljjYuNGVfloSShMXuAdBs7jfghKTZGXUpb7DNdK5tdu0gDvnC6pZiCoR4zIoc6z9FlRznuZfYeenmrecOTYBOHEagj24M5nMIMSHoqcg3eJ1zG8UXqYBJnLE=,iv:ahPbzb6o2i4HLv7gD79R3Bb9gsZmBMKTHhy42cPFyQQ=,tag:uMcxSqTnZ1OEytri05+/FA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
