apiVersion: v1
kind: Secret
metadata:
    name: pihole-info
type: Opaque
stringData:
    pihole-password: ENC[AES256_GCM,data:qafpxI88LLBRP+72YRY=,iv:mUbLCkYi5yejAItd6p2EUgqaWLBfzSz97pLt5ydHHLs=,tag:cd8+x1q/pn4VsB8gAKl9sg==,type:str]
    pihole-server: ENC[AES256_GCM,data:xQ4/wd0mFg0ENqT+4kD8V1Rq5eU=,iv:02Ju7bbxeefHU8Y0CdMBwciuX2N1T+wy8hzuP0IFp64=,tag:yakUkj2pQXXLgPSyDilmLA==,type:str]
    pihole-api-version: ENC[AES256_GCM,data:Zg==,iv:N6wAZBIccdpUWNUSuG9KAe35AqQmualmAHloUiVbfjE=,tag:fiXmuP+1WAUhKmhcraNQxg==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SEU0YWJuS0oxM2k1Kzhr
            c0pTTVFKdmdoeUZQUnF3clYxaHAzS05FaFFvCm9icUxJMGp6RDkvbGFGOElVS1Bu
            cEorV1JGcDMzck9lR0xhVjhSOWtydnMKLS0tIEhtSmFTUDVpdmtVaGxHa2xRcDFi
            UTFKYWNVaGYyekVoU2x5Y2kydDBScm8KmXD+YQ/l7ECRdO2PrVAn6QViowFH8HIm
            2h2cNqmdxCyyYaIPmCnqP9lR50ZJcwUb7entxjerbXzrG1nJ8pmk7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:10:32Z"
    mac: ENC[AES256_GCM,data:fbJolINdqKjJJnZRt2u7OQ+hviAenBHvQ9N3Bc89my0sxHk97jh454yD74h9T2KCEwq2xhAoH/GXD+3zKiLZSo4jQbgdfJU+xhZ4ozuGnUCXBKTKx7sbCqYEGqM3Qa4ShJzJHsw8ikrWMeVQ3RyBaHQbpPpn2Tzmu9PvyPdUw6E=,iv:pydnyCv+ThqXzLZ4TEWw5cRpW5ovRIkPfAlPmf5LEMQ=,tag:h/zNwvF/LKG+FkvRyhYIrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
