apiVersion: v1
kind: Secret
metadata:
    name: pihole-info
type: Opaque
stringData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:sYzG1G2EjLAA5uRrBDs=,iv:e8A0reQ70CR2n6vhYQ0A9ZxxpI8Tti5lT72B07lKtRk=,tag:+qqPPAhbXMAagrjnNb0NtQ==,type:str]
    EXTERNAL_DNS_PIHOLE_SERVER: ENC[AES256_GCM,data:BuEdWNvJSF//DIvTHkDrCk4STxI=,iv:4uwRYhmM27wk5wx7BEAwUEaHZpo7UbzeVK5ItPanMcc=,tag:aGYyjDOthvwMvG0k26R9Ag==,type:str]
    EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY: ENC[AES256_GCM,data:iYeLDA==,iv:QnhSERDXl0e4nXAyOZ+4QNJOqgeUfCoZ9u/RK3ClErY=,tag:M1fNhSziJu9mHTtVFNIHrw==,type:bool]
    EXTERNAL_DNS_PIHOLE_API_VERSION: ENC[AES256_GCM,data:AQ==,iv:aFtjBzn5EcNYgVm1VT5PCNuUuM5TQkqTecT1nTJJyAw=,tag:2Q0wV9lmoKbFPGGmhQndXg==,type:int]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eEVCMzJVNHMyN3lxUlFR
            cTUrcG9oREs3dFkxMTBwVisyTzlhNEpkWlNBCmNGUXUvY0VmS2I3M0RHNmRxN0U4
            Vk5EYkpRcElsSVRwa21xU3lpZXR5N2cKLS0tIHBhSUpveFF3QlFUVEh1ckdORXNL
            a3IvYTl2VWNDK3hEVXVoS2hsNGdNRGsKXWalSApr9oWvvcmJfMF9A8dZ+dF3kKVH
            t5X1h8C5sz6TP0xAeuETktRufyKt7Mtxqn7EaDjXTJtPb15euxiDDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:51:31Z"
    mac: ENC[AES256_GCM,data:tm8PVthoR1EP5iTo3MsBEEAUVvo8Bvz9pckl+oHUhj3ZQcTVb8hLjdND9sZY1XXpkbemK68NJoYpqvegWhSGZRFoV25paBJ9dDi4W6XcwbtepE7POwtNEOGNz6QGsVwC0q88TOZKEm0f+JtWK+b1XdW4J5I1qSYk0uGuSmMurJk=,iv:6nYSHQxU1pKPE9C4+ewdSOnZELqbwAzmqghAJtiPL5w=,tag:NZ2qsVFDBsqPMHAMYHKm/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
