apiVersion: v1
kind: Secret
metadata:
    name: pihole-info
type: Opaque
stringData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:8N0+Be2NiquR+VoH4hw=,iv:kZqcbcmmH30u1mpnBcZPWYGlja/HhzxiDMmK8A9G7hY=,tag:OgJW28GoVSUEhhU6C8Ku7A==,type:str]
    EXTERNAL_DNS_PIHOLE_SERVER: ENC[AES256_GCM,data:qgU0lGpEPcOWr/NFbxuqtLnQ8Tw=,iv:G+rfaz/2bX7uEN6NVL+BTIUcZExHmieXOs42lWv3y2M=,tag:XmvaTEd1Pl+fpmxmWIpQrg==,type:str]
    EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY: ENC[AES256_GCM,data:CPy0Og==,iv:y/U1+focLnWN+EJTpQC9m9VouhpqoAroXdjxnogwEN0=,tag:HlxUjzo+VdL1pbBivEtgcg==,type:str]
    EXTERNAL_DNS_PIHOLE_API_VERSION: ENC[AES256_GCM,data:Hw==,iv:ytJYMccnLowIHbfjmTv9DRPsINiIrzZ8avSzULokFao=,tag:noH4T8FMpcZUd3YYGEEEJg==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOczV3cHcrWVhjTUtBUy9N
            Y2JFRWVMd3pKU2FtcENPTDE3bVBoa1pRTWx3CnJnSXltdzhhakhQcERPeENCWEJp
            eEtnUVdCa1Z6dFRIeHRNeC9kZTB4b1EKLS0tIHBOR1h4UXoycXBsNngxTmpMeEVr
            Y2dKUkZjM1kya1lHRDVPeFNVTnphblUKT+nrggKI9LBSADJfEKIQHsdShhVxE0fz
            ST0wi503rNpsPg6Hv9H/7j38lxUgDnnWNAZQ3k2mGmbJoJuXO4wF0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:53:04Z"
    mac: ENC[AES256_GCM,data:rhGGZZuuqc2iPgooW91+0J0HcoNyNGpsvHgh9Jz8N3fg4E492LcQCg5C77oiF+857lLyIJCARMkv9wekcIlHBtu2wMVqw+KkIff9zAbwcUrjP5DisN6Ug3LwbUq1Fw8pd0Ofx8w7aSYg2CWMPglpMoB9LdS7m4FT4SROsDVSnOg=,iv:qK4YuuHBCk6GpMDyUWCGKwyFkNvBRU2xAvjT+xOKmEM=,tag:wuLSjY8GdtlmNRwtfMefOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
