apiVersion: v1
kind: Secret
metadata:
    name: pihole-info
type: Opaque
stringData:
    pihole-password: ENC[AES256_GCM,data:PHRHvCCekI0VkcEOSQ0=,iv:HPHC7yLrO49dxogCzgNHP7jfeKCg/6NbMq+hRmc6aYs=,tag:bTfPTe8Nvdkb2TYLBZ584w==,type:str]
    pihole-server: ENC[AES256_GCM,data:YfaeMP8DFOB4kqmNN0RmNFOEzm8=,iv:eumnKuiRerv4yIinxBU6EWQcZZM9A1Lw6tw4WWHCNl8=,tag:vlIieuKglJtEzJZCfqLm1w==,type:str]
    pihole-api-version: ENC[AES256_GCM,data:fQ==,iv:kPUUGFcdiFPfosdf0WaviYM/C1Grscot8rDep8muDCg=,tag:aeqGO9WwlDPC3KawLpuoAg==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveXpoUVNoM2lFdExkRnhj
            dmdVcFBqWHNiaTRPUzZYYkI0R3FEWHoyS0M0CkNvZlVPUzM2U053VVRDMEhrWEpl
            ZlVHQnR2dkFMMlRSaVpJNmRWMGt1d1EKLS0tIElmeXRPQ0JydFZSck9tOC9JRnlt
            Q1ZrSEd5SkF5RlNjRXMwZzBybG1aa3cKgWve/Ipchz2trAkObG+8SJWBh4YLEoTh
            dvWTykR0/oCfJ98VL1Xw8g4y3yb2X35VQe4lxg+uz4rB5YTsTmfKzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:22:48Z"
    mac: ENC[AES256_GCM,data:Geel6Jh9xXYitrHtaZw5syyEXf5BaUdCy+KqizsPeaJmcwpdhPdXnJDonLO+keKtg1vBXBYp+S1uKEUnozW77krP8V045u22ikGhUP3C2ak5DInozc4DekCBd1SXQ+w7L5/egY2hdelspeFqhT1WDuGr6WS4Fg/DdwwoNjh8b/4=,iv:PUAX026P0bQ6xcxHP1QGjrUFUfzVOsPtkxKTGMX8HN0=,tag:d65oXX8HD1AdBZixlxTUtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
