apiVersion: v1
kind: Secret
metadata:
    name: pihole-info
type: Opaque
stringData:
    pihole-password: ENC[AES256_GCM,data:Un4cOFs83E2qPsutxgo=,iv:wnBej82lk5H1y1NFdHNv9aLoK9Eo9+fWuds08RN4240=,tag:BstPK05b0mtyqP9bEwZFxg==,type:str]
    pihole-server: ENC[AES256_GCM,data:AmlhIWSM6Vw9+x6l812LK54TiYo=,iv:ukPh7pT2msgOt+SvWXhcJuDuB+9Ek5ppDu3LdeSCuh8=,tag:VOkanqcUiTHjM4NkZH4i2w==,type:str]
    pihole-api-version: ENC[AES256_GCM,data:sw==,iv:39bD5y23SpaIZxubnjasfXobDQtsJvXmrvz0gD9Cvsc=,tag:4SBTNZAnMXc5k2imnm9cxg==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdXVUQnlDWHJhOThQN016
            ZitIcEc4cXRENkFiV2JyYm9WWDhpc3JjQjBFCkkzcVk3ME4xT0w5dkFLNFlJTG9G
            emJMaGV6SzJ5UnZ6d1pvMlBVSkJtd2sKLS0tIEYxVEdPZVVmWmlMV0NJTmM5YlZ0
            QjkzanExRloyaGVqUWVlOHNYdWEyU2cKMfyu+AVChUlm2G7zZ+uvFg3akGanwf1h
            IQvv4AOeJxe32R4VeLN2UbDaGZb7uGStptHIlWHVAlEFEQXk5pAhpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:56:52Z"
    mac: ENC[AES256_GCM,data:FLPN0TA88kdkjbUfPIdMLv1rxJcgd+UCAnMt0o4nBFvBVOvYBbjZUbrf0rdjwRLDbJWwoYkIbPELuTZbQlgVcrMNOuLK1GQge8S2GapTFd9k2sNz1rTzUbifxQKQCCtp0k0MCO9SvG9UfJSdo9jxIuOMgdL2NKPk8tk3tm1poJ0=,iv:vOYdAoju3/aHqS2D1LfWW3jmYd8xDKImg/qTJhIpVB4=,tag:FRTxv1PHxtq9ucS5AANTKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
