apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base/secrets/database-backup-to-gcs.secret.sops.yaml
  - namespace.yaml
#  - ./mlflow
#  - ./sonarqube
#  - ./onyx
#  - ./minimaldo
#  - ./signoz
#  - ./owasp-dependency-track # High Mem and CPU usage
