apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minimaldo-aws-devsecops-runner-scale-set
spec:
  interval: 5m
  releaseName: arc-runner

  chart:
    spec:
      chart: gha-runner-scale-set
      version: '0.12.1'
      sourceRef:
        kind: HelmRepository
        name: oci-arc-charts
        namespace: arc-runners

  values:
    githubConfigUrl: "https://github.com/thakurnishu/minimaldo-aws-devsecops"
    githubConfigSecret: arc-github-app-secrets
    maxRunners: 3
    minRunners: 1
    runnerScaleSetName: "minimaldo-aws-devsecops-ubuntu-homelab"
    containerMode:
      type: "dind"
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.325.0
            command: ["/home/runner/run.sh"]
            resources:
              limits:
                memory: "2Gi"
                cpu: "550m"
              requests:
                memory: "64Mi"
                cpu: "10m"
