apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hjrq/p78oLMX7FyD6vpayIvlvy3kdK1vazuJwEiEhEVRPGlxYIqIof/dGr2YEfqbJ10zhKuNU89ClNwWIw==,iv:gju6bSH/Xhnn3OBNW8eEGg42iU3RGXuiR3IIr42lv5A=,tag:8uzPI9V0dy/A1MQ+YmMUyQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:plVZki57vRf1iEIiC0I3AMmxAIsZtBvL7Z5zasr0,iv:fSy3fFBHwzzpwc3rpSog22nIB+nGyQtu3n2GuITj3A4=,tag:rljWoJTkUg2PQrqYU46m/Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wWd5bjCidu2xlIXFBuuTAiwTGj6J4NVf+5v8PDT9dkzv14NdSOoi/g==,iv:E9mUG4o3OTl/QS/r/L8TDgvYgHmTFQwS35Xt5tGL2zE=,tag:KiP4A+z+BsQbKGyywesfkQ==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWGdhUi9xSUZNRExXblQv
            RGloYXNCVHVVUFJlUWZyTmFpSy9SNmtzZ1ZzCjhlMXEwRWc1LzhydzNTWXlFQlVQ
            ZmpoRDFzMkQxSU1FSGo3WEQ0MnhCVTgKLS0tIEpsQm1SOXliOTgxWlhEQWM2NFQ1
            ZnRNOWpWbkJldCtzQmdpbXhrQ3NFVlUK4qgn296XES/d2hXYTZo8NRcFe83Icmo4
            56OWrga8CG+EPUE5oNwM48akyGbt28xIZaPrVNxPjMVjjopvjBJzBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:56:52Z"
    mac: ENC[AES256_GCM,data:9hlR7F2cL1T4jNKtyttZbAO3IawtGA6qsCoroQ0Z0H4SsVPGCD4hUWTr3lEBYPrbG9lFujA3BJCrtZiAREnIZ4PXCzkpd9xZOKO3YWRnkG3mRx40HwWyc58Mt9lf/4Uf22HeVJjlmE+YJNcsOoi0/7Eg8Z4L1YjfNYbawGSpNp8=,iv:EK2XH6dmsb0bvR0CVc44x7aq+i6k1bFDy1PsHDW8vVc=,tag:FUsnHEfO64K6Wp2UZxlHhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
