apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
#   - ./mlflow
#  - ./sonarqube
#  - ./onyx
#  - ./minimaldo
#  - ./signoz
#  - ./owasp-dependency-track # High Mem and CPU usage
