apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn
  - ./metallb
  - ./metrics-server
  - ./cert-manager
  - ./monitoring
  - ./istio
  - ./cloudnativepg
  - ./eck-operator
  - ./external-dns

  - ./kserve

#  - ./traefik

#  - ./pihole
#  - ./actions-runner-controller

#  - ./cloudflared
#  - ./kyverno
#  - ./opentelemetry-collector
