apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:fgZ5DPKH55nk7/OFMso=,iv:6ZF0u7s1gYrW4wHOsqBFMERaaPQbtwWd+JTrIpufFJE=,tag:zndnIdqC7y+lOSOtilOTCg==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WTFFNHV0U3BMQmtDZ1NH
            bzhkUUoxdDNQKzlQYm1rRVhoNGRteHNrZjBFCnhRbStCMzdkRExTUVBYVHlwU081
            UEVKYTFhSmorZWxLK0tOaXBqUEJSVDAKLS0tIEhoZXRvcjdqV0V4aHpTU2dFbXpo
            dGFaQ1hXLzdnNXRZMW5rK0JLb04rZjgKFk/NNlbbWfsEq4AR6ThBj+IQ0TiDGO7Z
            tomu3PE/WOSjC++9dLIgLNochGMCgrpYZ1EtGtVdbn8bFTGFcvDwng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:22:48Z"
    mac: ENC[AES256_GCM,data:8XX10d03Ky8iWK6tD37XxpRrka99r6sCbAiYHz6rIe8CVSDzwr/JQTkQCSm6N9FidFgr5RGXeWipkgJXgV5HY5mucY6MqzbDn1DCu+6ncGkxXRlwEpC3NmRDljqAuzWnOoVeB7sP5hb1mURfE11UioURta2WyhVQUV5JRz1W6I0=,iv:s0sF5dt8Nzr8TBOd4onUhlwSsigYwqNaZ92G7Jxzp7E=,tag:Psf/Fr0u7lHx6uD/Xnfi1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
