apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:0X58+RKvSDGsTuSFEsQ=,iv:+DJ8UtbOhb3+iEcQA49i95++oxm/mhq61X/+Xi1BUTg=,tag:Aoc8Im9LWLF/S4jM5Vw2nQ==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QlFvMnBmRDFPWDc5T1Bh
            WUVYWDB4bi9NZzRScm1mdkxrdmlFdktYb1RrCno1UUJVOW8wTjE3aUg5RjUrbmt6
            bkt4RmtLT1Q0cW5oTFNYT3JHd0p5SDQKLS0tIG9sZUZVVzZqYVgzMXZVcytLdlFx
            ZjhpL09tTlc4M1YxV1VtM09DMjA3TE0KmM3FaYgaX2N8V1/2VyX3eccxrAJQ7Tzo
            uTtFvhW3MQatAFu1dNauPO+b2JoasbV7TAvi+QFY/G8hRiRBpuNlxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T14:43:29Z"
    mac: ENC[AES256_GCM,data:AGtLpC0+EL12T9+86Kxyo0Fx14VDBHaxHeQUfMvxm9RjbqNibTOscwIqJgOKY6rglu0I7/wd0VRx2lSJXJMlJ2jE+sK37Xvyua+eP0PKmQBRPZf3oabEj5Zj71gSo6Fu6Fi6n1CU6r5XSw2vzqeazvteZSZyVqgyj6A6i+cRnpw=,iv:suwgkjCAtEi5orzzFjA3jTwhbnk7xxcGqc94g/cCAv0=,tag:2YXZF6NLDGbj7uJzZYmflg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
