apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:JLw/Lpqq7yb5/WZdgIE=,iv:pv8J6cUow4jJIFqQFWYwGOprzq87f+62IrEujR/+N0c=,tag:SDm+I/6rrMENYOw8oHVkXg==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdXZUNW4rTXBaME1COHJk
            amhCbGNRZWFRdVVsOXJWZ0p3VXJqeWhNcm44CkJkN2Q0TVNPTUdWNUhmeUZlSzVI
            c2JCV0ViMGxXc1MyckdZWGQ0UG1DUTQKLS0tIHB2b2k3YnBBd0pOdUcxV0ZpV2Rw
            SXEyYzZNQ2I2K0ZyT3YxU3Z4S1FNU0UKWi8DzTbDatEgken1+hoTD4Bvmw6PqBnz
            EKJwxMtC6232M7OnVqmwgKFFeELEBMOrLKhEdRzInJLjr+PwvlEQfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:06:25Z"
    mac: ENC[AES256_GCM,data:9BRvIV681QOgY5gzxtaT1t8RyZskeVKUCBH3SIswdrsX+6pkSNTWHTEDIbZ7fhJvzzKhQ3He64YYHX7bqIe5TV3v7GTmd3wGS7+Q6Jj+9zMFwJavb19nZjYCsLHxCLfWWjuw5J5qYkRffnja0cUdaqFiRMejkkSffkuPAsYC9e4=,iv:TcC8k+nhNKndU9CVgKwt7k3FGzig6JouyeijBoMy58g=,tag:DaTPoNmGvm0oC8DxP1zpTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
