apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:FZcOJSutTrX9NGH3Xak=,iv:IS6EnQBYHBdCZDHJX2b81hbU6LYMAlcPjLJDoUq4WT8=,tag:bprbBusKILFMV0VhzfhQbQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMjBaUnVqSWd6ZldCL3Y0
            Y0hlcFpnRFNZam1TaXE0Zy9XNGRLUjJtSnpBCmFCVmFYYjQ3dXF5L3hDSE9QSDBr
            TnZGUTRCOWlRVkdzNFVzZTRKWWV1aEEKLS0tIDFpd24xM3UyWjlNUmorcGhreVZE
            QzRYMkE0RFNENWtoNms0TWMzd2FZaG8KBG6RfD9MQoOiE7nMU6m+hICzUWZhM7pk
            x2nhGQgKaUapiFrPBW7Q9AJ7smHYvfcrY27Cm8fPk7u/21CM2KZx2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T10:21:52Z"
    mac: ENC[AES256_GCM,data:vb0s0fWFy01OYEvMlfhSzgwrLGJpN4JdBOulLSdjovaEcH5KS/FshEI6B1Q1fiM6wQH21GKZrZcaVWmraX3Yv4q0Bah/VYzoowwSkT2s8QeI0vZaeJrk7xnEoEe7bCJbDMAtyM9c3PojQLzk1w9Fgt6luC2KHBB7xDL8ByNGbEo=,iv:fVCkFDUe+qV4t3nUIGoZ5xojcGn2DnAmhzsfDl3sJ7Y=,tag:L9E8xIEedWMDZyaiRSaajg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
