apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:FUhK5hm1gxDPtSlFlz4=,iv:jxUqDdrZ/ZicJm1pHcQioDVVrPra/nYXK5N5/tAokeE=,tag:PLaGlkzfuMiOjWGUDE6ZKw==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVHoxWExUbHYrRFl4Rmll
            N0FZMzFUN2czbUMxMXFhdi9XR2g3aVdrMTNvCmhVQ3pHelJvMFFsaW9saXVoQ1Ux
            Uy9uMm9TUTdCYjhDa3JwRUpMZVo0T0UKLS0tIEZ1L1VsSnIwdlNzeXM5Vlgra2ZV
            SlBCS2hEaHV5dmd2SCtRN3dhYzFLV2cKtMnIn379mNDXMJrmlvtXXetDxVdKgZnx
            u3rchmr1xrgiXaVFAqOIMxa60cQB8/n5oXvtxRXjDc4/qsNcIvaKiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T14:48:58Z"
    mac: ENC[AES256_GCM,data:yPUL58/SCMnIugsAivhYh8ZDXnP+X3Cn3oKH8OyW6n4K79nKp1uFAxREHRkuzEK5WtEXAlda1rbH+GOxVuxpzxU24IZcK0CWMPhL1ZVIdovNTVaTR1geSvpdfGizuJ4+u7DUUcB63XoylCcS7SsLNH4Z6F5I8Gt/1anjUcCwO+Q=,iv:aWntfN5DkVBlz+U/ftjk5nfz8sxfm8AT7uikC7E/9h4=,tag:KjOXcR37uvDoPd7u8kdrog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
