apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Nf/Rdx1rfhsQG+XrCL4=,iv:NZivk0OuafZ9Ru9PN+BJT8b3F2H2y2GP1OwscoELZX0=,tag:xgFlPAzqQlyQD9W9wBCf8w==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNEFmZm1OYmZQTFQzYWgy
            WTA3c0Y5bzNjSFgzSVRJWXRlNUdpTGxldlhRClRETjkySXowQisxRFVCUk5WZDNM
            RHo5c2sxQ3lYaGpjVW51SmxIM0xDL1UKLS0tIDk2L2g1ZXZxZGRyOThJdTc0c2Vh
            TlpMSWlaNXZ2Vk9LRmUwTVp6dDV1M0kKxoRmm0UagZX+lKXCSgB/ePNiMhng/dqv
            8kUKh2pbpoe1j5C71loY6rxlmi5TfRLMyI6QAOnhz7RG2Fwht7ZAOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:51:31Z"
    mac: ENC[AES256_GCM,data:zLRiPZxRh86K68PSUTMHwaQDiHXSW3vnKjzqxYcShIE9CRvsm6S2l6bwoj3UWSb9plV7xXKYO6by9blJFFpvGceJwGYEiwWbhfGbR3CREsCNuoY5EUHQ/taMbz600J3TmfABsUSBnEFzPePjbz3WgRjrJHjFETBXKKgpXOZZbiw=,iv:XM4zUeXWKkS478RD3gLM/sHdZKPpyLyx6x0jjMTccm4=,tag:j1pSnaD4GfTJ5H5R80CqQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
