apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: null
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTDFoTUZ1WDhtV3RHSjZa
            dGFsNWhUOWdVQ3NwQTJuL3VmaEZPUEE5OWgwCjhCL0lkQ3lEM2UwYjllcGtCWUxT
            dkdzUjRVL2ZsZG5qK1JzQVZvZUxDNkEKLS0tIHUvRWFZQ0ozWGdkSkFZNmtzQTNw
            SVV0Q0ZUK05zM3YybWRBYU9TTnhHb0kKdhlBGjcJm+6ZiO6AQhnRP57DoxOx5BHV
            Ymb/UhSxMGOc/IYMXSAUv9WL1lQhSDiJjg2KpyKNWlP4+ramPDJ+ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T17:32:11Z"
    mac: ENC[AES256_GCM,data:NvGGstx0grSOpYGHhpp4WdLYTlzqtmBxXo86Si2p597wn3Vb/730dSZtm7vOvc4pvT3dn9gRGKaWEAPoVAZM+4+fqErrXpc3BFLsPpQAq+0og7WD+PhUMVld5/ZPQUj18Yp1+xUJSePimz8e8y1B+BmzLEUD+53Qj/rks183nvI=,iv:7bP13WM35pSu1ujfRr7WGA7JVE3QtptX3PTzdgbQ+Ao=,tag:Aft3AESFWMWD7nsRYpGtQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
