apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:wA+4PWxZZS9YjzajB1U=,iv:awL7O2KimDBwymVHOtNT5ONyLJJurgPshsPwgs6Thn8=,tag:kRF3JC37ULV3DLcqCSGOZQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRFZHZjRNcHNybG1zT0Q4
            SE9PT2xsbktaZnhIbUpRZ05NS3ltTE9RTFE0CndRTjRkK2pGYWNhMmlYNUV4dzZI
            QlZnaWJmSnBQemQ2MHI4TVRON3RPeWcKLS0tIFpiMUlyd1M2dWlhUU0vZjBJY0I5
            VWdxVlduaEN3ZE9FYjltditlY01HMEEKO++Q2Fxv2DlbAuOLlsCpAtORw0Q5Vion
            9Dp3gFEMN8rZKD2uMioOIntVCDrU1R5s7DyTlthlBbxN4oXNwDboCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:10:32Z"
    mac: ENC[AES256_GCM,data:qevL5h0LbsPetBkAcm3MzT6OrGvDeleShnpZa748TkUeEu3o6pB3bGlRWc61b4oGveUUjKiYoPojUH/bSvEafJETTAE63q0Su2L6ApEgbuF/kJEr8mGUqGi4UzSx1nWCEg539B0j9LyEXbWteUGcTjQJUDD21H5oH9pRt7VpxX0=,iv:21m4632YBEZby9kK8MyDtqGUmrmkCGu6Sjuq2NfvVr8=,tag:BGgVmqWEs8s1tJRYK+4OlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
