apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:+ur+CqgDaaxzbpyylDg=,iv:gAKzUsLCXPRaiWWfuJxUfWTZptF1P85TT0ke9HRH2Gg=,tag:3DQKFS29Bz6xce66KT57yQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWkU5N0pIWW5MNFZLTnUw
            eG91V0VIT2REOGF1YVZjSlBad2Z4dlR0dEZzCjBNQnNDNW51WjUzNnNrZ3RaRkc5
            SE53ZitUUGZVUUxsVnRwR1FYQWtVbWMKLS0tIEtBQ2Rqc1ZLS1draHZCdVN3WndP
            VlhSYTZQVGdoS0p0bmp1SUg0MlU1K2MK6lTcL3zfLvgK9bchFxxHmyzhx1ClMNco
            H4FpVFFnpdaGnG5EmxdU/7Y9F1U0ZBgWgVMCjy6lW8OMaH2W6nudcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:53:04Z"
    mac: ENC[AES256_GCM,data:eSjkWqxKqdS5w9jeNR6LNa9LeU8/RyxhUhkuxZm6RDyR3ntAoz6cdVz/HYhXxv0HALsKyYX6pdt3P6yNYYk2Y6hBn+niVJwlMSF2MGm/QjzmOmRnfsG2nIqNqShEJ3hC8qjGCZsyuELUIWILVpJ08cti9Hdy34J9vXeCXpDg6/E=,iv:PJujsmI9RlcVMC9G0M0n70gxazFuYTCbquy8KAaSibY=,tag:sJoH3W+eyIm/Uf2AeTBcyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
