apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:/eNnHOTEgZKtZNr9jP4=,iv:25OotracYLp7aCSN68Zns4MiYj8HuTEusW33A+pJAxk=,tag:pjOpt1EwkLOSA2JzLIIxDA==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraVRGaDE4V0hqT1FIdS9N
            dmJJVFFCT0hlbnNwVXhremd5Ykp4cUZBcFVvCnJDN2RkWDhhZllzbzhnVmR0czRC
            K3hmRWZrV1VPb3lKQzJGR0ltc2FJTFkKLS0tIGttQjhWeSsrMjNuekljUkxabkVw
            WitHVjNoUDN5RzZTMlpzZ2VpNXhCUXMKBnRBGq1Gfv+SkR0JvwMg5JU+3Msw8IHC
            5PD5iWRoeYMzVruKFC7FtlBmq8BD0UHD3YBdKloGqoT9FvE3ztHUpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T07:47:02Z"
    mac: ENC[AES256_GCM,data:ExxCE3PI1R9r4BWpnTPWh3DhKkA22tuMsa44u9el2pxbGXLuZIRHuYsp/LCzW7mcjp2BeHiOAwcYCNGyCsgBs1X4k8+8pZT+Y3Rx9tlt53u27jpSeSOgBXiXGSGzRKL2iAL3sEQYNfEmheIE09jd5g2uvwpVDIgfhvljNcG7o0w=,iv:1Ev2z8Zq15H98Qu5Xi2+1f+mtFc4ydj7ly3zTIH4On0=,tag:qQiAU/dbAbPv+v2BwgAf9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
