apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Qy+kcfbatARLLu/eme8=,iv:cnrAFvSYSy8Wn7INdVLWKjUtokTP+b9kB6E5AxozMoM=,tag:uKvh8izluu830v0U9BZkDg==,type:str]
sops:
    age:
        - recipient: age1khzu05szp0um38uvn50knwv8w2puy64a9f6f3f0mjtc2lzpmzgqs7m23pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRlByMUlHczBKU094bU1w
            MS9hWWRBbXlxSEVpRDhJdXh0cXEvYmlzQUFBCmdocEJmU3JURGZ4cExDZ2FmVmpt
            WUlOTGg4eHFrRWZINks4bFdyK3JtUXcKLS0tIHkxMVpmeXRhaXJmWGZnMlFkeDkv
            YXNxWENEU2RtN1N1L0FXWGtoTVNtb3cKMpay+0iqktX85W4YsoCeAjh/hswVTxP5
            152JLaEBiDnXEboJrkrxrhkhriS4i3xv4NeNx6owYlzKc0Y54VUCaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T09:25:01Z"
    mac: ENC[AES256_GCM,data:gzXD28iYZVcRdDtGDskugt/fFWo2UHuhrGPAbYZ/gn9JaqR7xAumYrb5hOnJchMHCUnLO+/So6sAangmrrvoLU3WqhQRRH4lEKlQCUamBxwVwtdw1IQF+Bip1AKMUgms1miZYHD1tqXkmYsIsVjTs1VXMyRqMMdD+0zX9bfm8Ng=,iv:/1Lxzoq6p4L3tdbmYCWNaIG8bEIuj7LONt9pYc0caDQ=,tag:TiVeuAlGPPFo3n2LO0jsTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
