apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:KOCBemQUDwNs7Mcukdg=,iv:cbvtF5wrmTt5HY2uzgn+P0WT4FIkNfMN59s9eYsoIyk=,tag:KInomXy+d+jCO949b0AxIw==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YWwxYWZIS1BoS1BlenA5
            UmtYTTFTMlIrNXlSemQyTStuenFCZ2c5VVRFCkRvOXN6aWZNWlpFUlZ3S2psa0dT
            dVRQa0o4QU5jcW5OVnEwajF5RGlpc28KLS0tIGtlYm9GengySnNDMEpyWllrRFdz
            L1hvYzVuUmtQQndtd0l5ajAvcUJQbGsKq70adYZQjySLe/OFAUnndxdOs4dgDUkx
            +mU9jfqh1yfAMRmwavmxOQpok2mu5vlNOKBNsxjxgMRlVrWbuBk9eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T20:07:23Z"
    mac: ENC[AES256_GCM,data:lHV3gVd1kHubauw94xRQOCAyqR5IGh+wIGHVmN/Z1Lnw/WwzwaiYj0EJtr/JC5dp3/dMq2nzg23T5pd/btPllR9VdVEh2egqgXEJgE4txn2t4vza2AvgFhqDC0cTCWnCtj/JnUjQq0aYbvLJGfAo5E5g0XCq86vZa3DvOHd0SFE=,iv:u7Yv7lthJWA2rDsg61g1P7keNmbZxNokQW31ZRn/Xso=,tag:5BJ/B8Eu6R3hSTzzAs139w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
