apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:w8GKYhVHFyffh32mlOY=,iv:mhkeyLpfUrW/a+C3Hni+FJENdDLrNZJToUj6+vu662c=,tag:QfXp4uJSVmSdE5AaHNjtew==,type:str]
sops:
    age:
        - recipient: age184uxhteulqapkl0ue4lpyyn5pxlpwteynxp2367vykclxxzvxyfs6a66ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMmk4ME1lcjRicHVsRXJk
            Qmt1VXA4TGtlaXFBanArSlMvUjN1eWVnVUNrCndQR2V1MjVZUmE2OVVyUS9Va24x
            SFhjTnk1K01WZ04rL1BSWGN6U0R1VEEKLS0tIHBwc09sUXgxcG5RRVNtMUgxYTl5
            QS9ldTJETnJja2p3anh5MDF2ZXd6dEUKkHi9nsnqMGTEYpDOZ8HzSWnTUal6Pq/y
            VKTD3gWOgPGIKP3isRJoM69l7uqyBgPnLjGkWnSCHDmC0J9WHjiaUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T13:17:47Z"
    mac: ENC[AES256_GCM,data:eHrGy96Z0nhYJUB6IU2Thh0xU2XUbc51Hb5P+NyCqaEIDCXvHFw5p3A2wzIXAIqhsa0hsQnMElGDDWzM4go5B1SDz0qwzqguhpEFwjMIJ+meBG9HEXMsM5QUocgl0IwpZhgDm9Df+UREj2dHPds7gUcHEObpzh9I0xSyk/NWRhE=,iv:ZoNmYnMQuBJReXhENrx+1hKQZLwlMi768g/Naaw0hkA=,tag:908dH9Oox0W8pcFz1kBIcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
