apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Ef+LM1qeX3f+k3i4NJE=,iv:wjcjjjojoehC/5qXCkhkZJBA0nKGcZKZ7/7vzEZvxnA=,tag:rL0fEvXa1r5+qBLC5En8gA==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVjh1eU82MGRsVTY4RzlN
            YmhIN0p3OUcyVFlqWVc1R3RxSnB2QTlwVUJZCkg4aFRWQTRPUXFscitLcFpCOERC
            eFd3WmVwWk93eG92ei80c0tHY1NXMUkKLS0tIEJ0aEhuK0o5c1RTSDZDU1hOMjlE
            SzF6WDZCeGtlbE50V1VsYmVyaEw1VFEKnHSsMDA24kXLz2Pk5FP80p8bqGZ92828
            v4fK5hAa0NRSlWQX31R3RmS1bLWmMlubgQMx3JR5z0Ym2j0XFNYvag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T15:09:28Z"
    mac: ENC[AES256_GCM,data:AN+V7gLs+7K0jKwIbhtj4smtcA/A0+Repnwqu54LleTE0V0LLeZStPENIEOO06f6H4l0QKZjiO9EUgg2M1DVCwWHI6UzUfbTDAPSqwnIoYfjcuO8WYG66uP3dQXIaK1wppig0Hw5u481MC4cB2BZzb6N19gJslv4OTAWu6P6EK0=,iv:7ZmZlGGTUnk3E1sNGT6TaQAtS/kLsB8BaiVmDb+CSLc=,tag:qfmNX5rpRMiXMjfp7HFdzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
