apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:nYjKxSPkOncU0tv9oCA=,iv:V5VfSLyDYJJ5e/Mt+9s165T/KrPe+eQIkR3y5aSwRJU=,tag:MIQnhWNWeA5I6iW2w2iPaQ==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ1JkRzR5emhoYmxNTHFT
            ZHpXMGhteGc5blU0N3VFZFpZdVg5akdRZ3lFClY4T1ZLem5YU1lSQ3UzemdRbGpp
            bXo3SWR6NVN2RXlaNFQwZEc4ZjFKbm8KLS0tIFpEOTNCSG9wZjdIczc0aUtrSnhD
            MmRBeGM5dVRaWnRnZkFoZk01UjhYTVEK8ffL6DSH0jGJLH4/Xo00Vcs91FU/BzlL
            Biwxjw6fQINevsXEr4TSHRsQXEmc+pYs8IF3/yXDVin9hP9SeJ5+tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T09:08:21Z"
    mac: ENC[AES256_GCM,data:E70jQEaLSR9iIrt0oaE86O7P5p3RHpIJlE3gyeOe8j3v09UrMztyHvb7u/VIyyFTL+mmg0TiMINRiPv/wJmx3zLFlYA4KfNtSSD36kfJ1zcLGFw2kbAHbj1QrQJH8Yms3H1/O10jKIhVS78viW/Xzpq4qcEVTc4Tg6xRUU8B4c4=,iv:Q3ZMI6AwncaIsitjpWdumuKB0WjTeiFHGojepRtTk3I=,tag:QBaD8c17KKZpPxSwWeNrRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
