apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/sonarqube
  - namespace.yaml
  - pg-cluster.yaml
#  - pg-cluster-backup.yaml
  - ./secrets

namespace: prod

patches:
  - path: release.yaml
