apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn
  - ./traefik
  - ./metallb
  - ./metrics-server
  - ./cert-manager
  - ./pihole
#  - ./cloudnativepg
#  - ./actions-runner-controller

  - ./monitoring
#  - ./cloudflared
#  - ./kyverno
#  - ./opentelemetry-collector
