apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn
#  - ./traefik
  - ./metallb
  - ./metrics-server
  - ./cert-manager
#  - ./monitoring
  - ./cloudnativepg
  - ./istio
#  - ./external-dns

#  - ./pihole
#  - ./actions-runner-controller

#  - ./cloudflared
#  - ./kyverno
#  - ./opentelemetry-collector
