apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn
#  - ./traefik
#  - ./metallb
#  - ./metrics-server
#  - ./cert-manager
#  - ./monitoring
#  - ./cloudflared
#  - ./actions-runner-controller
#  - ./cloudnativepg
#  - ./kyverno
#  - ./opentelemetry-collector
  - ./pihole
