apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: longhorn-backup-gcp
spec:
  backupTargetURL: s3://homelab-backupz@us/longhorn
  credentialSecret: longhorn-gcp-backups
  pollInterval: 5m0s
