apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WtWu8POSy30RaHb1sAENVXqwufaej79Y9d0u+sz3LclpZkQNUNwZESDsyFmfTv0QJP2oQKlz4W86LaIIdQ==,iv:xw8T6mW5+MSd63wtVl/6Yxy6/H82W8aqF59Y67PMQeM=,tag:bPFo6x3eZlFtMwIN/WoAtw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:I6ei+GoCZ096CaK/HEKX/dSjHQ8Pl9m4IskKv/5a,iv:VVcX6cCt28AOE5IyLojPLgFDOXE7YxgdjujdziLnqYM=,tag:R+ArqF9zKLzuhDmUvBHr/g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kx33t3NET7Kop/Kvbj7SVetn+AeCdDg9H1L3SdmPmHDX1j/iW8O5HA==,iv:ov7+OYLdeWVMAgP21AxqA4+lRfXjuwly7Wa1RndfFDg=,tag:i5CnJRgtfn3Gk+n1OHjd2Q==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQUlvRXh6Y29ETm1qeC9t
            VFNhdHB6WG1MTURIT3JBUkdmNWNIenRKM1I0ClRhelBjbDc3dDFmN1dRYjl4MEpJ
            cWVOcGwwSVVFVFNGNlJlSjBRTjJUMDQKLS0tIDNqZHVCV3pwVEROMzNxc3dBaldG
            N01aOGM2SGhDZkNHU2pTNjBrMzlhYUUKqGoXFsqKXSUoN1lNQISU6UdXwGfPqyC4
            cVfnV7DTmXoe3iLs4JiqTPsvlP9s+YQ+9wIrhpgEOlciawSlaf3GRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T09:08:21Z"
    mac: ENC[AES256_GCM,data:huUJt7FWXBoNkG0Ngm2kCqpPMH3vsIRkrY8mkPNqTgdMcv8rWqGWghREPA12wcWr4aDDy1QdVrmwu9phaQBB1iLSOfmkYx4m7On7j1k7Q/4gu17YXbuMVbj+EkL5xAz3svKbxp8hzbLqN9D8tNQgOAB6Hv0Jlt4d/ZDlzRz3ISQ=,iv:idMu7qdfKKFQ/Lr/kLwKi/kb7jXEvjYKtcWOFOlFxy8=,tag:x9C/GUuK7OtQma+4sSoUFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
