apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5jPHqlbvrj4UDTxzac/ERynEXgFWHhgLIfiCfm+eUrT3r0V3H7dmuXJ6qB3u2nj3+QGKogi2c7voEZToEA==,iv:k3jTnjLBPW0io9zeeF1wxUinfuVhkqtm/BGYhG8Ayz0=,tag:s2eeu3H0A85QqxW3xiJVnA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:tQIfnDUfA5AR8CqUMFFYHK06/SC+bQp7PWLVGo5+,iv:j0Ng9MRY17J4UoaxZtzHbFjipvOfMTIAyQjtM/cF6vw=,tag:U4ondubP1fsK/jAB6zSwUg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bQRyPYeHKoMZJlso7pm7OxlmDT++XDLnBFGre1KkwEdq50NvBWR5lQ==,iv:/yZ2kmIxEfQnfwM6ywDgoORgbGgXPFKwjUhkt7Fqtjc=,tag:J8Hx+1E+5IL+aLG4b4VFZQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRalJhUkJWYXJmd2l0WGJ4
            NmNHRDdsTEl3VEROYUd6djZlMTNCRFNlTVJVCk85KytlaGhadGJwR0dCQmUwM0VS
            eS9IQkQwYzhadXdhSEZlWkRnbEJzdkUKLS0tIFZXcWRXUWdaeUlyNHhnRzJTRlVE
            K0lXcGJDOEZ4NkxFWEN0bENmKzY0UHcKSCVTFXF/pR6T8USrVMQr3BlvB9mtA/SF
            60PBgwjLjNxDH/3QvaF80XmL740+FgIOuTI7gBa/9oa9McGyTk56nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:53:04Z"
    mac: ENC[AES256_GCM,data:g2D0VcpB5fa516f0omtyaLpMwjzwNrUnBGrD1n7gYDYFIsaN0lqJR+OPGAsf6cVfRYPtgaMTNcd18ZTV3Qsz/xWXK1yAE63NW6/YgPKljuGRUrvYuehi5CdGLAtjOGBbhubqKOzDj798hjum/KSE8lDjYbQEc0EZKrdRQT4jFq0=,iv:YwWnaY5gVyPmn8ZPN0VtN01U7tzJp/AAHG6vr6Fy4Lw=,tag:R/L9jukhrHr0vZ27EvDzvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
