apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6jA20BeOTJbJy0kak1XjYslapFoXg1rL8m/NC1l86vCjBk59hrmI/Us0XxQC/DycCA4aFzwKsldA8EOOEw==,iv:9Bs3jqDE9SZGHPLreWnzQNAsBNfLOD+KB/ixkSHIk2M=,tag:t3Y16PQgJu5LLV/hyOXpqw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:OJdizsZYYi0B/b+ACUZZH6gJ0Fy/urpGZu36Z/y3,iv:y//mhJ1TGexCRPM4GgphgoSKkBxidMHywln2XvMGVAo=,tag:d9+LUecWfA24zhvbigT33Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pdgNHWvv9q7irQ3g+xQRTz//QSV+oPluOaX4YdhkoOmqax8w5isghg==,iv:Uwfp/aa22CwORdLC0E5dwnQuBg6/v3+5hnTTRtE1L+E=,tag:37cJhPKFu0TrgR/ioRnvsQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcWhGZHI1ZnlYUExrc0o2
            SWNCUUpZUFRvdWtyWnhwWnBNNHh1SUN3RTBzClVmMWFROTNWaFBFMXVNNlhNYUVJ
            T1NqMGpRRGJDa1BQK2tvRS95VWdaeG8KLS0tIC9UWkdaa3BiRTRIaGJ6QnM4dW9B
            UkxzcllDOGxidkFsTWM3SmFKdUdCdzQKwzVUSRGA3lL+MS6eR1EwV7MrB6otaRGH
            ErAYJCIyUH2ic0rGzNi1hsJFRoYAdIWC6/WjvFQxR/CZMHReOteEbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T15:09:28Z"
    mac: ENC[AES256_GCM,data:/f3ojoIlWYLGDjUM8VGLKNCQs2JKQedYE62uJbonKntve7+Bb8QhFbgg62r/ug72XPfhsi2ZtbN6tT0BS+WTcWXAL+iL6sKncSVC3U95STktucI/k/Z+sJS37AovXIrDOefe1FA4uIJS5LfAcrRKRrlSKoq0kJ5T95BxI69QjFg=,iv:cc1jHAEqNnYICl5UbFVwifU1FMRPcJsu7eB5Jl+6T7s=,tag:nkNT5TIx2DPOrinxOsEfew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
