apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DaxVn7LpmVELURax62yGxbIMygZARtDMx+AS/FAdoUqZoDq6qlYyXVqHuqKqLD/ImUxOwdkh/14/3EWFYQ==,iv:F3/pyjjQHGWBQeco3HzLQp3XxaYLD+HlOTCWJXJlTPM=,tag:350bi4k6OY1s4gbkvNEEGw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:yK51OZYchyLZ+UU6Xs3t3E44zf/DmnyDiW4/IOqH,iv:qnT98XwwSmCxNZd44jb0HaMe+VfQ3UuE9ecbBRpXh2U=,tag:NCtP2RY+PgIbxClexysNXw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nkwktwoqZDdm7gCZT5nDSXBsbic+Kwg3pUemKofvNDFWqVUM+zL1Sw==,iv:FL5YoASM3wtEkRhsF+J1DFqZy/locOwgqCs/69AJj9Y=,tag:9ur0YJrSRDoMdwRmijgLqg==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUXFGY3h1UjJENnZUVWVr
            VDNyMitrUUttcFd5N1VHUWRqaDhCUzZIdGdJCnE3akJoQndaaTNRTlZpaTNGT1pI
            OEFZNW9jRlFlZTlrYmJiR2p5b2dtYVkKLS0tIEVaN0t3RGE5a2NxOEY1OE5DMFRP
            UGVJNEN0RHVUcWJNdlVvQmVGRGxtc3cKkiRTX4EuvCSf7YPhV185RPAxVtIuL0ls
            Gkl0rBepJSpAaUIqoJBPUorxVV5LI4NI31Q8BhyWYctXQscmMcIukg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T14:48:58Z"
    mac: ENC[AES256_GCM,data:QOz6IWCVSceUY62rU8xun8+J4yjMST8nYK6whSi+dgFu9PS72vXkozswioHxB+te/c2R/oQdEU5Bsv+9bva08j0eRDZdPN6iMW3pyQkYTZnZk4rkrcIMLwmb0OgkGsmyPNCdbaYILSjHKNmTlq4GJLmtCZ+Oo5fFvvzCZM6oKRI=,iv:Z4v+lPmHMOHzh+7z4qUVjn5Bwh1tB0aiKQ7VxKEzOcg=,tag:s/q4VKRjvHCZWlzFBLSHMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
