apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XDi/TTA5YQMD7l917P24k8UpRXA7gwKLn027kjB6it1+7A6gKAzqP6Evl1uoiyeldUkbIogRh026vBKNiw==,iv:jczXT2T9to90r9Ag+ce8fc762i4Ap9bJjLOiv/pspF8=,tag:yKW+DB7tFsKe+LJlMg3M2g==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:00cqrlWKILeEAH6K68fTbWDAQDqnEirisauB9KrD,iv:OfwqbE3VeVDQzib+AKPCk/SQa8dyw0VT10kbre07qAU=,tag:U8vBF1jzmwi6x2xxJrDJ/Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ihvqs6pp/mudmiOQSBx7bPmCR1R2PLChi+AbXLv+vpYyM/9nULRnGQ==,iv:e2b48t9xVFaCEnivoKRboHcLRj7a1MPd4zdphIf6IVE=,tag:DpQ9E3byjn8D9jvFxAmZTQ==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWmFWN28rRXF3L0NaWWFM
            eWh5UlNOQU1QcGd2STlJUGthTXJqWGVDN2dvCkpHTmVQL2ZkZVZZTUNKbzNOa1RP
            VTlZRzhLQTZxemNDaEhPNk54K2I1RTQKLS0tIC9WdFUyYmRSRm9uQllmK2VLZ2hp
            Y3hKNFlEVEh4SUJxaFphU0dEWXJFWmcKzGxtWyB3I5nRxc9CJzPSOivPzs2nRV++
            jo8drgq9WQn8WZauZdRb3elFCMYUxom3jpTi05FlO+d201N4xXuBxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T14:43:29Z"
    mac: ENC[AES256_GCM,data:t39eP1HMp99i8VVxcaS1eK/KkWPYeaJzAw1ZXxfieaXsDaxfLlO38mG3Fn7EwYYFpkpfwOWRuL7s12T2V17IiPN4pEZFREUSJTGpAtzfLgyCDCe9dI5H6goAsKTJqMIcUdCPcgcYxiPryVocgC846i7874WloQGeGfoofky4o3I=,iv:/TXmGd4W7yVrHvI4HM4xByX/Gn8aA1e1Ibj+DHj1qdg=,tag:ZlCfh3DWviee+gn08y1xug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
