apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hSXVEok696Op1nTj5ufBpo5NCuo5CWXtzCfz3h73x7SLV96/wrqetG5U4/jCnjjswE78TZNXQ+Azxe0RFQ==,iv:r3arv1gfRQCbdlnn0SAtiUC8NEMHKHWB7eF39lK5ESQ=,tag:Mx+6E2uQskqos9k5R5kguA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:+k5vrpGf6hk8JWiAJCDVqF6qCn9i8bltKA9/2L5s,iv:wTxFpLRoWzZiNDdNaZq5IgHJqZLuUDPaa1eAx9wFrkU=,tag:mlnUGx6SnD0cEYnuGVZxXw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:z/lCm7piBLXUsYrMtBOhlQ5YDey501cFIkYHAQOa9NNG88yKn9ZYFQ==,iv:4ZS+lkpYZ3O/jPEX7sDbYkTOSyMnFvFwHMtHbXUoAd8=,tag:tE9ecsyLhMLwcbV8NeuYeQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5alg5SWhXYWwzNEd6cGdH
            b00ydUg0NzBHT0U5RjkvYTEweGRVWENNaVJNClE1OUs1M0R0a3BSQXRNNld0UVNo
            M2JaWU0rZnlOOUNzVjBDRHRUWE9IMHcKLS0tIGM5cklOVS9IZUIzczA0b1pHWjVL
            Z1g2ZUk5cDFlSEk3SFZuR2RaYWVqNHMKEGiX/6UdC54J6DevKKwDs9VpQryqkYWC
            UvfmTlNo8qiVGWE75SQkMYzCWaufH3oLWwTRXLS9hocQbV7u0q2pFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:22:48Z"
    mac: ENC[AES256_GCM,data:GEss8QVNabZsudN/rTFIxcBk8FFFFNvE+AxNOFTwXwNfKmwIsb9JGxJw4MJqL/spUnlDyGTzhYzF44WTHn2hTZSbGRpJMct3Mob2jc6EnYl8Q1CrPyESLA0QtNJLJitxmQeb//W5UMWx0CHtfZu/Q8BaoAp/PewVT4cKJbQTWZI=,iv:dHFfzCk7X6kxf+EZH22BC2Ja7RpbUN5853PU88F1CXw=,tag:iMb4NPXaHAR7rROaAi9vCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
