apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:huMkSSdpktstDFJapbs5xlCmer6RPl/uMrEhySnjCuGE5RxkyVKvEQGGdqu8IyePcvFt8BKy7nlP+orvog==,iv:k/xmU4gb0upeApQB4duQLDLwxZnkXU1GHc50iglvafo=,tag:/7Lkm/gmaw5y2APK+zhZXg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:0sWndrXG3yJns3gagZjM9L8EaAuTYubpxpFHLWmQ,iv:pYV7c9afOTWY1YV8PLf6arc+9slWp+V3y5sGtciaVAI=,tag:FeRK0EP4FSpssem8MXud6w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NAZMg7voFOkNxlFNcooAJxrfcw3O1KyB/s5Wfe0uWrZja/Vk/qfq3A==,iv:NZHwF/+GNU7h/E+oJagaZOLgf3RjgXSIo5HbmleFB2E=,tag:nLnR/i8k/b7acoGCkOa8yQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SGVBSTdnYThPc09jL09u
            SDIvemVQd0V0dEdZQjRySTliQ25XOVYyU2xZCm0zcGgrYVdDNURlTURHSmlSaUtn
            SWh2dTFGc3E5QkkvWFhDa1pzUkg3dGMKLS0tIDNmM1VrSjRTc2lGSFJOQnVib3hK
            Y3VwUWdHR216VXhhWExJMjhSMUd5WGsKfNjwe8nT/rBLBKp4uABbfZVs1pCh+y15
            VZXeSeCnhG1r2V2cOkxbOAhJZWOEfrLllrAVznPUakomaFPFb7Tf7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:51:31Z"
    mac: ENC[AES256_GCM,data:XWxFFZDo4PPJT5Q5YqFhSrdKZs1vhwyQlCzRcYbHYs13maJAZ8pAzs2AGk8BHjuZ2g/ceig8qe17Kp0WFfPjnmYAchwIzVzSLZctlS6maDJ6p4eFdV7Shddnz5Kr4RtcfgTOcXtwTPGaxX2BR9sI2zYiS4FWAo7hEGoBLvbTxkQ=,iv:yRv0KplNfsAnsVUOmXVoopTgZ8UeOUJYr8dDOHjbH54=,tag:c7Ja/SLacmz2UP4GXHPouQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
