apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3oUu8VqNLdkX/XNuNOa5PCjwKae/MtaomzgI1loZ/yDXojYxPr8KandOyhTCtQUVKe/yehF8BNRB56sMvA==,iv:qYhxnJVU3J88aNEkO7bvRoR6qEGQ+4AqkI9frcx2Oek=,tag:GIBex/PBfQCFllukSOxGNg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:z5Udq8x28BBuB+Mij1Lhndirbe00VWbtBx6l/gyo,iv:Ok+yFrDpgrywFYf09ZanpC9YF/fYaa6Wl97yHFx4Hjs=,tag:83bK1ah+w6VuOTUSHeN/pA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iBb5923yvILMWerHl726uE8lVmS90tzK76spiQSZqnNIv/USifASaQ==,iv:rNYRSFfQFnzGnwCAgdPWfAZoaosO1ZzDzmeVX27/1zM=,tag:xPO52loUCExLQaIWzw6iAQ==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN1N3R1pWM3FRbDN0cjdG
            elN6QllYbEwrcHRBSXZWVGM5VHBBTW1nQzJVClY4TlZVdmhwNE5tZ0RHL1BuWWhV
            RDdqbVpyM3RSamV0ZGwwcENvU0lNYm8KLS0tIHFLZWZyRDh4dFVrZXVzK2x4OWk0
            clhCNEkyckJpZFpOb0lBa0IwTWc0ak0KV76Hf87T8oMTf39KFtpsOlN/5xVEZ7c3
            uABZFeMNf1xYQSTMbE4WgBk/dlK7uEx2qEYfp9pMVCz7UfEML2GH8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T07:47:02Z"
    mac: ENC[AES256_GCM,data:h5jHPIJa+FeVSe9edo7my9MjxAVSlgEd9SO0B/3Z/A52IBiCHMtiCrwCRBVhPbYMuFqXSTo7YvfzGLVxwc8O5M3VJoFkD3un9zbgrVMNKKqpcLSryiYWf9w3JFq069faj3fZ54WaV7IE/aFdADUkQ8J50vDnv6kQ0Qs8s354AtM=,iv:MqD1Ckfo04VQG+r2Ox6//JMjgB5s7DBJzJLsO6He6rI=,tag:YvHDPQraH75Rk+bzcOI/cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
