apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:g4yf/KLuJ+kGEKvR/M5aA2g2fTvlIkU8v17ejR271ZgSMQVfL40EoAw5o2dcqR0ciiZRb4rDZ8OnDAaYcg==,iv:3m6tzgezzwK/2cxnt7pnzhFPhxNUlh5haRR2/WmGTw0=,tag:4aGsLwoyvX9Ucjav5HH5qg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Pjc8ZfA9AkO2ZsUAZ05+Mgno968JWp+JD5RrN3Ow,iv:N+/G+vdwtQbO7YPHf6KoqAaBWeqKMzR0ixajVsPanBU=,tag:EfI/k/jbJSWH7N546qvouQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VlZr1AiBDZjXTsRidZakD5xjKSKQRJga88RHb2F3kPi9LDv+B0sTBQ==,iv:WiexrPHQiXdXXdnKTtcoJKju33JZyEvgJ72Q9GOhbCQ=,tag:dpNvjtJRH7plM6neJLUnVQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTmxSSEV0UmNmOGJOc0pq
            MjFYL0ZLL1dHUzJjM1RZc3lmWjIvcGhmN2lVCmpRWGJpajFWWVBvNFhBeU5Zc25R
            MW1oS2xUajlzMTl3Y2QxU1Z6Q3ZRQjgKLS0tIE5aZW1CRnRNVFlGVng0K2NJd01K
            Sy9PektJTi9KMFZvZTRwYS9XenYwbjQK09VZG0c9UOAEBFi/dCKdZWOnB0naMIMj
            PO9kaAXvytply7uT5kQ8eeiHUHJXflN+O438rzwzLQ1/DSl1kamDfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:10:32Z"
    mac: ENC[AES256_GCM,data:YBEiiYpTsLl4RzZTN3pJCftP0wh7k9/R8LpNGajaphV8NNsiisgdDB5+oDDvdNd2ef7egwholb0lMM4IkHDCbAN/SZBJmUJ/ZYuT+XAacSmUoMXgeZI7BqZiwryl30NcqI46iqwY7eoGLDn/PGkYb4PPmq0N6wqJ8d7IV/TgyKw=,iv:3eS3Ij13/d+vk6tKiS7qgJ6Yj12h/O2e8A69GK64SEM=,tag:JYOed+ivBtWEs0+Mh//8iQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
