apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AucgL+hI1Mz258LIQWXrV+StUZr/5K+ONVSPNynGcMcrWhv+mRIphCypqRUfi8BauUHrBqsuUkvo2mpcDQ==,iv:9eg+QxFEyCA48YhYvfuyrmfQNyo52mplrblEi7SJP8A=,tag:T8AsUlRN00qMlCS4p6spXA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:lz7S1BDl22L28reNkTIVunYBxaDVMzHUlfLUxAF8,iv:g/aAG4XwP1HZvmNWBDTTb4cmde8qYyMaVFfxRdWoAtk=,tag:ukBODFiqjDz0GiVc8ytLCw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cTrNtAl+C0BqQTn6dWaZUpM73Vlxmy1+Z0x96kHdJibJfNfrHGbZ4g==,iv:R38V+k+fmU0Rb06IAbddo/+UeY6lMUpggdnWEniVlMI=,tag:e88h/Y7OsWbrrqzAuZGpng==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRDlsaHZocStEdW5sc2VZ
            Z0QxeFczMkQwV1Y5Nk8xOEdmcFFHR29LZjE4CjU1TmFUWmttOWVwVGJWYmh3Vm5H
            ajlubXlLakNjV0tNZ1VKZ1JLbjdTUTQKLS0tIHBvdEM3NDdqNSt0ZE52THh1OE1O
            dStuMzF1N0lPSUV1K3VjdnlmSHUwdncKlT5PccUFiApgW6/cbmk4GyHOqmerTVr6
            GzKjgGl/GwWMZh3c1w3J2py40gkzUAACA/SqFjxT33ayTH/HYFV5iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:06:25Z"
    mac: ENC[AES256_GCM,data:GmRE9YuOuLaiV21K+sMlDiMqRkYzTWXi1rdBVirtgDafPOo4ccIH91iTNMoq2x2T+l9cJ3cDoOFagerGlU+81sKXWCudeAUvAK09d2Gea3ueGx2pnubJC0vhs0EWRK/42PPJll9zqUKvgJaN5rUueiuRt0PCwSqBm+4Cfsqr918=,iv:B6WmE3zfVl669ua8q92x2eO/OxE9M/p3EPgSB3wP7HA=,tag:WDl3ta+zqFTtFkzKN282TQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
