apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2QNskEH7faWeEB1iDbKSZvQrJvT8DK1P92peQPbagXZ1sAM5vqVSBBO0/+dEyJ2FtsPTpbUU8mgYi/yDjQ==,iv:itVJYzf0yYsq4Jrj0jCD4av8lYMxNB2lZRbLIhHgMFM=,tag:kMoPUyaXw9oPV7m7Q5Smig==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:VUyY3vDP/YVbTgife0bO4gJUrXcHW0prq3XsBl+d,iv:S3JfGm+Nu+GeuYUg/7BXtOJYKVu+GCTfojQfY47laiU=,tag:6TH6pUrHQ5A6aGJ2IxUrhg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HFxkuiGdUxxc54rF+dpxQyftpvavNdr79SS3f4GOiQyDEibG/SAPWQ==,iv:8EU60ogzhy9yZssr8H2Qg8ePx5TIHq2jU0/Ksn7v8yU=,tag:SsfDdvbDNbnBNRmIcbR8vA==,type:str]
sops:
    age:
        - recipient: age184uxhteulqapkl0ue4lpyyn5pxlpwteynxp2367vykclxxzvxyfs6a66ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ2VaTUFPRU9iUHJ6MmFW
            Y05Hem1rdC9aV0JXbjd2Nkt1K04rRVBVeG1BCmErU1lieUhGVkhncTJVSmFTQzFE
            bWdLT0dudzREbFdUa1c0bzBrQmVSOWsKLS0tIDFRWUp3bXNzRUF5bXBKd2xJL1dM
            MzFveW9iL3dtWjBtTlFrdXhsNWo3WjAKG8gpCWoXSdUie5sQ4NNUJ3yFjZ7Qa2RL
            X70oSUjGgX0/3150Z3Ig7jWm19c0qe0qb0Zr8evm0utSacXIaeSdPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T13:17:47Z"
    mac: ENC[AES256_GCM,data:fpxFxhn07EUKIzDH5r8uYSh1O7Q/pOOW2e+K33iVN0cEQh8d1IxDoMMjqOzO9zfgmzTJlEuWORgP8lbunI6h24yC289djMUBtAkzK1tX7hrxYr1r46T7zl/fWh0i9TtYHACjmdXb5hOKALDMqiJbwdVP5l2jlJFXY/nZFMv9l4g=,iv:5vDQoe0d4fXwRWLLeJmDpgT/qwU5H0rjxSoTtm60+3g=,tag:fR/SHQk6YlQePJfo+0cHkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
