apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8MRULV5Xa/D/ZLPNCnv2vcoRAMnhuoT3j6oja8nnoDXbMwPJxeCpCKjDyP0Bi29cJBOaNXy7VgMkcwaCyA==,iv:2S2B59YbkjTglQtupfX1zZLpMikExyVp5Ht79gS8JBw=,tag:WJcynMEZGNk5STJCJoH2Fw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:LDHk9it+QF/7NTOxKpoMxsol4rw0rN06vGRIGwa1,iv:guH8OUV4W1F9UjsMcS2Ppa5Z1hymes6kaYFNRbWltAk=,tag:GUARhfpLrZZzJvYWo9g53g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:D+poGOYpyeKcOtkYM/nlQgYzBVVct7VgXgI1IBP1lInMBhnnY+nwpQ==,iv:4467LnxBDR8N2akphcklBtNHQ8dFxyvmy0oPuvdLHWw=,tag:Fa5JfQRH++FfAhEU/fiqjA==,type:str]
sops:
    age:
        - recipient: age1khzu05szp0um38uvn50knwv8w2puy64a9f6f3f0mjtc2lzpmzgqs7m23pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UTk4elU2alBnckYxVS9a
            dHNXd2xVZUF4VEZtR05oMnZ3bmhlWlc3dHlnCnYxZXZJV2EzRU9SNUE2Und2OEZk
            ejg0SkkyQlRoWlAvWGlWTTFsOE1lc1EKLS0tIGJKd2lyMmhKNWpwK3hBZnc4U2FZ
            M3diZnZ6K0NNVXFRZ1BLc253ejJ1QVkKtFBk9YSbJ10rEWJME+TGabn5e9vTAj8N
            JenZ/dF1LYsnSpYUEIhpM8xM7bsliyv1Hh7BjbShSyFdMQhLgwYaNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T09:25:01Z"
    mac: ENC[AES256_GCM,data:ORaxwdACbAoQmc+xnfKi76krVV9fstwbvvvmu9n/+9Qkuxgfjd41QY7kk/+E+9gYXLHQmq69jWH66HaaCWb0Qyrt7MZ+w8LCMw1FyIWl2lUEazSNwLmnsEMG+obQ8hhR75IQLf5FiD/LDoG/nlhk3LGhECHSsNodscFtkQ1gK3s=,iv:ebQEquhoJLpVT2ng0mOyUz4/P3VsRIEUUPrBFZjJwdc=,tag:mLw/Ac5kq30rjv9xRuc8Ew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
