apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wsx9XjNEOobv+EVJ23kgePDZYynXxv7cizUBsjnSyIoHhQq84X0ja6wGv9/cJ9ipJ+aW9BJP7kTgkrVjLA==,iv:NNSimpZC5QTpDua4RWOp2ZIOrUJISNvXxYC5sWcppjE=,tag:jMLAb4yQDr8a0MrP0OKffg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:JsWI0k++d0Tv5PcoAlaXdtpDTBgRztmoc6Uo8B0A,iv:z3snE+B8BES1hwDpzjkkyPlvzBp+nCLyLV+wEtVQh6o=,tag:aoXt4VfDP4hxROrSXfPj6Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BMGP/WTwcGuTDnHmVY1v9gPGxsucEhCTSPpzGYTEfqm2iVYLl7+x1A==,iv:YhI3TpPEamfH4tnUM2PXe+1jiE3rRlpBfovA562vjiQ=,tag:GPAhF+2zzOFb2oukG/XyXw==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dFZoVVJJNXdpSWFkZ2d1
            SjVqODgvQWRRWUxxNVRTTGtOdG1jL3QraHpBClBJcloxTXZWSVR0cEtnUVVzZHIx
            Tk01U3Y3dDRCQmFNVlRDZHd0YlY2ajAKLS0tIEJXUmV3WElEN3FoUXBhNi9IU2Iw
            OUFhWlFWMkVVZmhDRjM1U1lrSjVUUjgKG5yYgmQdhHPFJ1fet/X4DRfzsQ2uwQYD
            KyxcHUD15kDIhYu3UPMo/gcMtuSfg9OT4gIxL1ofymz5qZzNALgOZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T10:21:52Z"
    mac: ENC[AES256_GCM,data:6U4+CPm//+NIxTwt2vF405WkEu/IK6PO/Wtqk0SJPXCXM/lRZRPcJjOHMSg+RQ26l5lhIBzH9svoW2hrWBfmgfByL8O/pLxlYX1BRqO4wWWJUNx15rB/z0sVSQi3i2iEPcClzdpgSSK9JCrkTAnIiR468sJgSX0p+2kb4IDKDUg=,iv:JO1EX5xAxSmS0dvlCDsTDCPAoHK807Jmh74X+U10EF4=,tag:j7aJNPhIqGUb6a075A6b4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
