apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:2yGSa52LMMnFOOTcSm16dWmvpl9J7WUkLONYGa2/dQAtSLQyyPt/4A==,iv:SSAz4maRAREzyvSST/o9LRCTHk0PXcL0PPtbXb9FfQ8=,tag:rZB8UmJVrY+Gk4Q2OlHmLA==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSnhqQ0NkM3J2b3pnWmFt
            WFJhMUN5cit3T08rQ2U2d3NuSEQ3b01YS0hBCnNDSjJEdWZMN2JDWnM1Nm1heXBG
            d2tQM201SkxkNTdvTjZIeHI3MHlObUkKLS0tIDFrYXdReXhPaGVvYUZRL0g0MDU3
            MTZqcmt2S1dibXBBSzZoSnlBTDNQNUkKpsntctdX7wWLqCuA1D+o46xMBvbTOZUb
            i88pqL3GWwRkMBzZKAJF9dw8sKx/JtdWv8yilTYg2wmgmbqk2Q60Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:22:48Z"
    mac: ENC[AES256_GCM,data:d/J0yCA5nEY6wL//Tj+z/dWEy35N4wHHLHkRczxRazCtnc7o8VJeKpiRHCHDgJ3phpDNoDoaK574z1LXnrToXb3UFGDAqLdyOSQ2iNQ1tFSr4XNYh10HtxIutKm7W2NzjQfxjW47LWwKGEQImhssH8rdWvT+by9W9RsdXO53I6s=,iv:AE+FPjllI0JCiWocwqxPbMfv4H7Dn2kpnGkOlTpfuys=,tag:JUSxbtCyMP5c0FGDF9rGSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
