apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:mX3HHZyZALNreEU3QsfBP81gQuaRJVOE0qtj/vnTm+LaEtQ1kUDnJw==,iv:q7YyjhFZaE35gHRuOCSMNxbnOr9JLzrUDoiUKC8iHXA=,tag:kSE+1vKCW/QzDli/eXP8aw==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbGhMMGZIVVFYQlN3aUNN
            QSsvOTVVUmlPMTVxMmVITVVJdlZ5NnJmK3g4CkRuSjJmOEdIUStTazJzQ1FiUXg3
            S2g2cFU0RmZHbnRmVGJRYWdzaTRqY2sKLS0tIGIvb0JSQTFtd09sQ093Sm5FL3dF
            YjlaSGVEOG5JRTIxTjlSbHJzdy8wL1UKBvxJm1tmQz5k0Whmj5ZBdwXlXyUXW3XU
            W46jo8Rb5X6N0U4LU2xspujgLyJlOnlz0Kf6+Utc3k3UzKKuIA0Nvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:56:52Z"
    mac: ENC[AES256_GCM,data:9rgNO44UwY3eHRbuEBxjtcyujVy1ANK1UT++dGWcW4KH0ccYn4dBxiNe6z3erkx12JMpDgzOPK+9xW8AxsAmOnAwz7QFNPT1u2B+kdeY0gthVNNgGkCybbit4lRDddrhwhsXz1Y7Gn0Q9I27gYElYOS8vDc5I3PO738+AiprU18=,iv:N6vO6meHxP60NusDbY/jtHPAUB2gOig8AHeBmhwsLqk=,tag:2UZq6iwF6Aw2yNvPC7j8Ow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
