installation:
  enabled: true
  calicoNetwork:
    ipPools:
      - cidr: 10.244.0.0/16
        encapsulation: VXLAN

defaultFelixConfiguration:
  enabled: true
  bpfConnectTimeLoadBalancing: Disabled


